
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.rtdd.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.entity.BlockEntityType;
import net.minecraft.world.level.block.Block;

import net.mcreator.rtdd.block.entity.W23BlockEntity;
import net.mcreator.rtdd.block.entity.B98BlockEntity;
import net.mcreator.rtdd.block.entity.B97BlockEntity;
import net.mcreator.rtdd.block.entity.B96BlockEntity;
import net.mcreator.rtdd.block.entity.B95BlockEntity;
import net.mcreator.rtdd.block.entity.B94BlockEntity;
import net.mcreator.rtdd.block.entity.B93BlockEntity;
import net.mcreator.rtdd.block.entity.B92BlockEntity;
import net.mcreator.rtdd.block.entity.B91BlockEntity;
import net.mcreator.rtdd.block.entity.B85BlockEntity;
import net.mcreator.rtdd.block.entity.B84BlockEntity;
import net.mcreator.rtdd.block.entity.B83BlockEntity;
import net.mcreator.rtdd.block.entity.B82BlockEntity;
import net.mcreator.rtdd.block.entity.B81BlockEntity;
import net.mcreator.rtdd.block.entity.B76BlockEntity;
import net.mcreator.rtdd.block.entity.B75BlockEntity;
import net.mcreator.rtdd.block.entity.B74BlockEntity;
import net.mcreator.rtdd.block.entity.B73BlockEntity;
import net.mcreator.rtdd.block.entity.B72BlockEntity;
import net.mcreator.rtdd.block.entity.B71BlockEntity;
import net.mcreator.rtdd.block.entity.B70BlockEntity;
import net.mcreator.rtdd.block.entity.B69BlockEntity;
import net.mcreator.rtdd.block.entity.B68BlockEntity;
import net.mcreator.rtdd.block.entity.B67BlockEntity;
import net.mcreator.rtdd.block.entity.B66BlockEntity;
import net.mcreator.rtdd.block.entity.B64BlockEntity;
import net.mcreator.rtdd.block.entity.B55BlockEntity;
import net.mcreator.rtdd.block.entity.B49BlockEntity;
import net.mcreator.rtdd.block.entity.B275BlockEntity;
import net.mcreator.rtdd.block.entity.B270BlockEntity;
import net.mcreator.rtdd.block.entity.B261BlockEntity;
import net.mcreator.rtdd.block.entity.B260BlockEntity;
import net.mcreator.rtdd.block.entity.B25BlockEntity;
import net.mcreator.rtdd.block.entity.B259BlockEntity;
import net.mcreator.rtdd.block.entity.B258BlockEntity;
import net.mcreator.rtdd.block.entity.B255BlockEntity;
import net.mcreator.rtdd.block.entity.B254BlockEntity;
import net.mcreator.rtdd.block.entity.B253BlockEntity;
import net.mcreator.rtdd.block.entity.B252BlockEntity;
import net.mcreator.rtdd.block.entity.B249BlockEntity;
import net.mcreator.rtdd.block.entity.B248BlockEntity;
import net.mcreator.rtdd.block.entity.B247BlockEntity;
import net.mcreator.rtdd.block.entity.B246BlockEntity;
import net.mcreator.rtdd.block.entity.B245BlockEntity;
import net.mcreator.rtdd.block.entity.B240T3BlockEntity;
import net.mcreator.rtdd.block.entity.B240T2BlockEntity;
import net.mcreator.rtdd.block.entity.B240T1BlockEntity;
import net.mcreator.rtdd.block.entity.B240BlockEntity;
import net.mcreator.rtdd.block.entity.B239T3BlockEntity;
import net.mcreator.rtdd.block.entity.B239T2BlockEntity;
import net.mcreator.rtdd.block.entity.B239T1BlockEntity;
import net.mcreator.rtdd.block.entity.B239BlockEntity;
import net.mcreator.rtdd.block.entity.B238T3BlockEntity;
import net.mcreator.rtdd.block.entity.B238T2BlockEntity;
import net.mcreator.rtdd.block.entity.B238T1BlockEntity;
import net.mcreator.rtdd.block.entity.B238BlockEntity;
import net.mcreator.rtdd.block.entity.B228BlockEntity;
import net.mcreator.rtdd.block.entity.B217BlockEntity;
import net.mcreator.rtdd.block.entity.B206BlockEntity;
import net.mcreator.rtdd.block.entity.B196BlockEntity;
import net.mcreator.rtdd.block.entity.B195BlockEntity;
import net.mcreator.rtdd.block.entity.B194BlockEntity;
import net.mcreator.rtdd.block.entity.B193BlockEntity;
import net.mcreator.rtdd.block.entity.B192BlockEntity;
import net.mcreator.rtdd.block.entity.B191BlockEntity;
import net.mcreator.rtdd.block.entity.B190BlockEntity;
import net.mcreator.rtdd.block.entity.B189BlockEntity;
import net.mcreator.rtdd.block.entity.B188BlockEntity;
import net.mcreator.rtdd.block.entity.B187BlockEntity;
import net.mcreator.rtdd.block.entity.B186BlockEntity;
import net.mcreator.rtdd.block.entity.B185BlockEntity;
import net.mcreator.rtdd.block.entity.B184BlockEntity;
import net.mcreator.rtdd.block.entity.B183BlockEntity;
import net.mcreator.rtdd.block.entity.B171BlockEntity;
import net.mcreator.rtdd.block.entity.B170BlockEntity;
import net.mcreator.rtdd.block.entity.B169BlockEntity;
import net.mcreator.rtdd.block.entity.B168BlockEntity;
import net.mcreator.rtdd.block.entity.B167BlockEntity;
import net.mcreator.rtdd.block.entity.B166BlockEntity;
import net.mcreator.rtdd.block.entity.B148BlockEntity;
import net.mcreator.rtdd.block.entity.B110BlockEntity;
import net.mcreator.rtdd.RtddMod;

public class RtddModBlockEntities {
	public static final DeferredRegister<BlockEntityType<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCK_ENTITIES, RtddMod.MODID);
	public static final RegistryObject<BlockEntityType<?>> B_25 = register("b_25", RtddModBlocks.B_25, B25BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_64 = register("b_64", RtddModBlocks.B_64, B64BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_110 = register("b_110", RtddModBlocks.B_110, B110BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_148 = register("b_148", RtddModBlocks.B_148, B148BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_49 = register("b_49", RtddModBlocks.B_49, B49BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_55 = register("b_55", RtddModBlocks.B_55, B55BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_66 = register("b_66", RtddModBlocks.B_66, B66BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_67 = register("b_67", RtddModBlocks.B_67, B67BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_68 = register("b_68", RtddModBlocks.B_68, B68BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_69 = register("b_69", RtddModBlocks.B_69, B69BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_70 = register("b_70", RtddModBlocks.B_70, B70BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_71 = register("b_71", RtddModBlocks.B_71, B71BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_72 = register("b_72", RtddModBlocks.B_72, B72BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_73 = register("b_73", RtddModBlocks.B_73, B73BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_74 = register("b_74", RtddModBlocks.B_74, B74BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_75 = register("b_75", RtddModBlocks.B_75, B75BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_76 = register("b_76", RtddModBlocks.B_76, B76BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_81 = register("b_81", RtddModBlocks.B_81, B81BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_82 = register("b_82", RtddModBlocks.B_82, B82BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_83 = register("b_83", RtddModBlocks.B_83, B83BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_84 = register("b_84", RtddModBlocks.B_84, B84BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_85 = register("b_85", RtddModBlocks.B_85, B85BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_91 = register("b_91", RtddModBlocks.B_91, B91BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_92 = register("b_92", RtddModBlocks.B_92, B92BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_93 = register("b_93", RtddModBlocks.B_93, B93BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_94 = register("b_94", RtddModBlocks.B_94, B94BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_95 = register("b_95", RtddModBlocks.B_95, B95BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_96 = register("b_96", RtddModBlocks.B_96, B96BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_97 = register("b_97", RtddModBlocks.B_97, B97BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_98 = register("b_98", RtddModBlocks.B_98, B98BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_166 = register("b_166", RtddModBlocks.B_166, B166BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_167 = register("b_167", RtddModBlocks.B_167, B167BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_168 = register("b_168", RtddModBlocks.B_168, B168BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_169 = register("b_169", RtddModBlocks.B_169, B169BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_170 = register("b_170", RtddModBlocks.B_170, B170BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_171 = register("b_171", RtddModBlocks.B_171, B171BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_183 = register("b_183", RtddModBlocks.B_183, B183BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_184 = register("b_184", RtddModBlocks.B_184, B184BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_185 = register("b_185", RtddModBlocks.B_185, B185BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_186 = register("b_186", RtddModBlocks.B_186, B186BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_187 = register("b_187", RtddModBlocks.B_187, B187BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_188 = register("b_188", RtddModBlocks.B_188, B188BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_189 = register("b_189", RtddModBlocks.B_189, B189BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_190 = register("b_190", RtddModBlocks.B_190, B190BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_191 = register("b_191", RtddModBlocks.B_191, B191BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_192 = register("b_192", RtddModBlocks.B_192, B192BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_193 = register("b_193", RtddModBlocks.B_193, B193BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_194 = register("b_194", RtddModBlocks.B_194, B194BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_195 = register("b_195", RtddModBlocks.B_195, B195BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_196 = register("b_196", RtddModBlocks.B_196, B196BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_206 = register("b_206", RtddModBlocks.B_206, B206BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> W_23 = register("w_23", RtddModBlocks.W_23, W23BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_217 = register("b_217", RtddModBlocks.B_217, B217BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_228 = register("b_228", RtddModBlocks.B_228, B228BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_238 = register("b_238", RtddModBlocks.B_238, B238BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_239 = register("b_239", RtddModBlocks.B_239, B239BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_240 = register("b_240", RtddModBlocks.B_240, B240BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_238_T_1 = register("b_238_t_1", RtddModBlocks.B_238_T_1, B238T1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_238_T_2 = register("b_238_t_2", RtddModBlocks.B_238_T_2, B238T2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_238_T_3 = register("b_238_t_3", RtddModBlocks.B_238_T_3, B238T3BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_239_T_1 = register("b_239_t_1", RtddModBlocks.B_239_T_1, B239T1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_239_T_2 = register("b_239_t_2", RtddModBlocks.B_239_T_2, B239T2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_239_T_3 = register("b_239_t_3", RtddModBlocks.B_239_T_3, B239T3BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_240_T_1 = register("b_240_t_1", RtddModBlocks.B_240_T_1, B240T1BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_240_T_2 = register("b_240_t_2", RtddModBlocks.B_240_T_2, B240T2BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_240_T_3 = register("b_240_t_3", RtddModBlocks.B_240_T_3, B240T3BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_245 = register("b_245", RtddModBlocks.B_245, B245BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_247 = register("b_247", RtddModBlocks.B_247, B247BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_248 = register("b_248", RtddModBlocks.B_248, B248BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_249 = register("b_249", RtddModBlocks.B_249, B249BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_246 = register("b_246", RtddModBlocks.B_246, B246BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_252 = register("b_252", RtddModBlocks.B_252, B252BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_253 = register("b_253", RtddModBlocks.B_253, B253BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_254 = register("b_254", RtddModBlocks.B_254, B254BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_255 = register("b_255", RtddModBlocks.B_255, B255BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_258 = register("b_258", RtddModBlocks.B_258, B258BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_259 = register("b_259", RtddModBlocks.B_259, B259BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_260 = register("b_260", RtddModBlocks.B_260, B260BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_261 = register("b_261", RtddModBlocks.B_261, B261BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_270 = register("b_270", RtddModBlocks.B_270, B270BlockEntity::new);
	public static final RegistryObject<BlockEntityType<?>> B_275 = register("b_275", RtddModBlocks.B_275, B275BlockEntity::new);

	private static RegistryObject<BlockEntityType<?>> register(String registryname, RegistryObject<Block> block, BlockEntityType.BlockEntitySupplier<?> supplier) {
		return REGISTRY.register(registryname, () -> BlockEntityType.Builder.of(supplier, block.get()).build(null));
	}
}
