
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.rtdd.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.rtdd.item.ZiluolangItem;
import net.mcreator.rtdd.item.W28Item;
import net.mcreator.rtdd.item.W27Item;
import net.mcreator.rtdd.item.W22Item;
import net.mcreator.rtdd.item.W21Item;
import net.mcreator.rtdd.item.W20Item;
import net.mcreator.rtdd.item.W19Item;
import net.mcreator.rtdd.item.W18Item;
import net.mcreator.rtdd.item.W17Item;
import net.mcreator.rtdd.item.W16Item;
import net.mcreator.rtdd.item.W15Item;
import net.mcreator.rtdd.item.W14Item;
import net.mcreator.rtdd.item.W13Item;
import net.mcreator.rtdd.item.W12Item;
import net.mcreator.rtdd.item.W11Item;
import net.mcreator.rtdd.item.W10Item;
import net.mcreator.rtdd.item.ThedriedfishItem;
import net.mcreator.rtdd.item.ThebeerItem;
import net.mcreator.rtdd.item.T15Item;
import net.mcreator.rtdd.item.T14Item;
import net.mcreator.rtdd.item.T13Item;
import net.mcreator.rtdd.item.T12Item;
import net.mcreator.rtdd.item.T11Item;
import net.mcreator.rtdd.item.T10Item;
import net.mcreator.rtdd.item.SheepracksItem;
import net.mcreator.rtdd.item.SheeploinsItem;
import net.mcreator.rtdd.item.PorkribItem;
import net.mcreator.rtdd.item.PorkloinsItem;
import net.mcreator.rtdd.item.MugItem;
import net.mcreator.rtdd.item.LegsleepItem;
import net.mcreator.rtdd.item.LegcowItem;
import net.mcreator.rtdd.item.LangmuItem;
import net.mcreator.rtdd.item.HuoguangItem;
import net.mcreator.rtdd.item.HamItem;
import net.mcreator.rtdd.item.HaiyanjiuItem;
import net.mcreator.rtdd.item.GuojiuItem;
import net.mcreator.rtdd.item.FutejiaItem;
import net.mcreator.rtdd.item.DeadsheepItem;
import net.mcreator.rtdd.item.DeadpiggItem;
import net.mcreator.rtdd.item.DeadcowItem;
import net.mcreator.rtdd.item.Dd21Item;
import net.mcreator.rtdd.item.Dd20Item;
import net.mcreator.rtdd.item.Dd19Item;
import net.mcreator.rtdd.item.Dd18Item;
import net.mcreator.rtdd.item.Dd17Item;
import net.mcreator.rtdd.item.Dd16Item;
import net.mcreator.rtdd.item.Dd15Item;
import net.mcreator.rtdd.item.Dd14Item;
import net.mcreator.rtdd.item.CostillavacaesItem;
import net.mcreator.rtdd.item.CookedhamsItem;
import net.mcreator.rtdd.item.CleaverItem;
import net.mcreator.rtdd.item.B79Item;
import net.mcreator.rtdd.item.B77Item;
import net.mcreator.rtdd.item.B263Item;
import net.mcreator.rtdd.item.B230Item;
import net.mcreator.rtdd.item.B203Item;
import net.mcreator.rtdd.item.B181Item;
import net.mcreator.rtdd.item.B161Item;
import net.mcreator.rtdd.item.B140Item;
import net.mcreator.rtdd.item.A9Item;
import net.mcreator.rtdd.item.A8Item;
import net.mcreator.rtdd.item.A7Item;
import net.mcreator.rtdd.item.A6Item;
import net.mcreator.rtdd.item.A5Item;
import net.mcreator.rtdd.item.A4Item;
import net.mcreator.rtdd.item.A3Item;
import net.mcreator.rtdd.item.A2Item;
import net.mcreator.rtdd.item.A28Item;
import net.mcreator.rtdd.item.A27Item;
import net.mcreator.rtdd.item.A26Item;
import net.mcreator.rtdd.item.A25Item;
import net.mcreator.rtdd.item.A24Item;
import net.mcreator.rtdd.item.A23Item;
import net.mcreator.rtdd.item.A22Item;
import net.mcreator.rtdd.item.A20Item;
import net.mcreator.rtdd.item.A1Item;
import net.mcreator.rtdd.item.A19Item;
import net.mcreator.rtdd.item.A18Item;
import net.mcreator.rtdd.item.A15Item;
import net.mcreator.rtdd.item.A13Item;
import net.mcreator.rtdd.item.A12Item;
import net.mcreator.rtdd.item.A11Item;
import net.mcreator.rtdd.item.A10Item;
import net.mcreator.rtdd.RtddMod;

public class RtddModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, RtddMod.MODID);
	public static final RegistryObject<Item> MEATHOOK = block(RtddModBlocks.MEATHOOK, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> CART = block(RtddModBlocks.CART, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> CLEAVER = REGISTRY.register("cleaver", () -> new CleaverItem());
	public static final RegistryObject<Item> HAM = REGISTRY.register("ham", () -> new HamItem());
	public static final RegistryObject<Item> LEGSLEEP = REGISTRY.register("legsleep", () -> new LegsleepItem());
	public static final RegistryObject<Item> LEGCOW = REGISTRY.register("legcow", () -> new LegcowItem());
	public static final RegistryObject<Item> COSTILLAVACAES = REGISTRY.register("costillavacaes", () -> new CostillavacaesItem());
	public static final RegistryObject<Item> COOKEDHAMS = REGISTRY.register("cookedhams", () -> new CookedhamsItem());
	public static final RegistryObject<Item> PORKLOINS = REGISTRY.register("porkloins", () -> new PorkloinsItem());
	public static final RegistryObject<Item> PORKRIB = REGISTRY.register("porkrib", () -> new PorkribItem());
	public static final RegistryObject<Item> SHEEPLOINS = REGISTRY.register("sheeploins", () -> new SheeploinsItem());
	public static final RegistryObject<Item> SHEEPRACKS = REGISTRY.register("sheepracks", () -> new SheepracksItem());
	public static final RegistryObject<Item> THEDRIEDFISH = REGISTRY.register("thedriedfish", () -> new ThedriedfishItem());
	public static final RegistryObject<Item> THEBEER = REGISTRY.register("thebeer", () -> new ThebeerItem());
	public static final RegistryObject<Item> A_1 = REGISTRY.register("a_1", () -> new A1Item());
	public static final RegistryObject<Item> A_2 = REGISTRY.register("a_2", () -> new A2Item());
	public static final RegistryObject<Item> A_3 = REGISTRY.register("a_3", () -> new A3Item());
	public static final RegistryObject<Item> A_4 = REGISTRY.register("a_4", () -> new A4Item());
	public static final RegistryObject<Item> A_5 = REGISTRY.register("a_5", () -> new A5Item());
	public static final RegistryObject<Item> A_6 = REGISTRY.register("a_6", () -> new A6Item());
	public static final RegistryObject<Item> A_7 = REGISTRY.register("a_7", () -> new A7Item());
	public static final RegistryObject<Item> A_8 = REGISTRY.register("a_8", () -> new A8Item());
	public static final RegistryObject<Item> A_11 = REGISTRY.register("a_11", () -> new A11Item());
	public static final RegistryObject<Item> A_12 = REGISTRY.register("a_12", () -> new A12Item());
	public static final RegistryObject<Item> A_15 = REGISTRY.register("a_15", () -> new A15Item());
	public static final RegistryObject<Item> A_18 = REGISTRY.register("a_18", () -> new A18Item());
	public static final RegistryObject<Item> B_2 = block(RtddModBlocks.B_2, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> B_4 = block(RtddModBlocks.B_4, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> A_20 = REGISTRY.register("a_20", () -> new A20Item());
	public static final RegistryObject<Item> B_6 = block(RtddModBlocks.B_6, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> B_15 = block(RtddModBlocks.B_15, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_23 = block(RtddModBlocks.B_23, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> B_25 = block(RtddModBlocks.B_25, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> B_27 = block(RtddModBlocks.B_27, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> B_28 = block(RtddModBlocks.B_28, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_29 = block(RtddModBlocks.B_29, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_31 = block(RtddModBlocks.B_31, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_33 = block(RtddModBlocks.B_33, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_34 = block(RtddModBlocks.B_34, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_35 = block(RtddModBlocks.B_35, null);
	public static final RegistryObject<Item> B_36 = block(RtddModBlocks.B_36, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_37 = block(RtddModBlocks.B_37, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_38 = block(RtddModBlocks.B_38, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> B_40 = block(RtddModBlocks.B_40, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> D_1 = block(RtddModBlocks.D_1, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_2 = block(RtddModBlocks.D_2, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_3 = block(RtddModBlocks.D_3, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_4 = block(RtddModBlocks.D_4, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_7 = block(RtddModBlocks.D_7, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_8 = block(RtddModBlocks.D_8, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_9 = block(RtddModBlocks.D_9, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_10 = block(RtddModBlocks.D_10, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_11 = block(RtddModBlocks.D_11, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_12 = block(RtddModBlocks.D_12, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> A_19 = REGISTRY.register("a_19", () -> new A19Item());
	public static final RegistryObject<Item> D_13 = block(RtddModBlocks.D_13, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_14 = block(RtddModBlocks.D_14, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_15 = block(RtddModBlocks.D_15, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> A_9 = REGISTRY.register("a_9", () -> new A9Item());
	public static final RegistryObject<Item> B_51 = block(RtddModBlocks.B_51, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_52 = block(RtddModBlocks.B_52, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_53 = block(RtddModBlocks.B_53, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_54 = block(RtddModBlocks.B_54, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_57 = block(RtddModBlocks.B_57, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_59 = block(RtddModBlocks.B_59, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_60 = block(RtddModBlocks.B_60, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_61 = block(RtddModBlocks.B_61, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_62 = block(RtddModBlocks.B_62, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_63 = block(RtddModBlocks.B_63, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_64 = block(RtddModBlocks.B_64, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> B_77 = REGISTRY.register("b_77", () -> new B77Item());
	public static final RegistryObject<Item> B_79 = REGISTRY.register("b_79", () -> new B79Item());
	public static final RegistryObject<Item> B_86 = block(RtddModBlocks.B_86, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_87 = block(RtddModBlocks.B_87, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_88 = block(RtddModBlocks.B_88, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> LANGMU = REGISTRY.register("langmu", () -> new LangmuItem());
	public static final RegistryObject<Item> GUOJIU = REGISTRY.register("guojiu", () -> new GuojiuItem());
	public static final RegistryObject<Item> B_102 = block(RtddModBlocks.B_102, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_103 = block(RtddModBlocks.B_103, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_107 = block(RtddModBlocks.B_107, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_108 = block(RtddModBlocks.B_108, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_110 = block(RtddModBlocks.B_110, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_111 = block(RtddModBlocks.B_111, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_112 = block(RtddModBlocks.B_112, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_113 = block(RtddModBlocks.B_113, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> B_120 = block(RtddModBlocks.B_120, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_121 = block(RtddModBlocks.B_121, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_124 = block(RtddModBlocks.B_124, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_125 = block(RtddModBlocks.B_125, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_127 = block(RtddModBlocks.B_127, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_128 = block(RtddModBlocks.B_128, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> A_10 = REGISTRY.register("a_10", () -> new A10Item());
	public static final RegistryObject<Item> A_13 = REGISTRY.register("a_13", () -> new A13Item());
	public static final RegistryObject<Item> DD_14_HELMET = REGISTRY.register("dd_14_helmet", () -> new Dd14Item.Helmet());
	public static final RegistryObject<Item> DD_14_CHESTPLATE = REGISTRY.register("dd_14_chestplate", () -> new Dd14Item.Chestplate());
	public static final RegistryObject<Item> DD_15_CHESTPLATE = REGISTRY.register("dd_15_chestplate", () -> new Dd15Item.Chestplate());
	public static final RegistryObject<Item> DD_16_HELMET = REGISTRY.register("dd_16_helmet", () -> new Dd16Item.Helmet());
	public static final RegistryObject<Item> DD_17_HELMET = REGISTRY.register("dd_17_helmet", () -> new Dd17Item.Helmet());
	public static final RegistryObject<Item> DD_17_CHESTPLATE = REGISTRY.register("dd_17_chestplate", () -> new Dd17Item.Chestplate());
	public static final RegistryObject<Item> DD_18_HELMET = REGISTRY.register("dd_18_helmet", () -> new Dd18Item.Helmet());
	public static final RegistryObject<Item> DD_18_CHESTPLATE = REGISTRY.register("dd_18_chestplate", () -> new Dd18Item.Chestplate());
	public static final RegistryObject<Item> DD_19_CHESTPLATE = REGISTRY.register("dd_19_chestplate", () -> new Dd19Item.Chestplate());
	public static final RegistryObject<Item> DD_20_HELMET = REGISTRY.register("dd_20_helmet", () -> new Dd20Item.Helmet());
	public static final RegistryObject<Item> DD_20_CHESTPLATE = REGISTRY.register("dd_20_chestplate", () -> new Dd20Item.Chestplate());
	public static final RegistryObject<Item> DD_21_HELMET = REGISTRY.register("dd_21_helmet", () -> new Dd21Item.Helmet());
	public static final RegistryObject<Item> DD_21_CHESTPLATE = REGISTRY.register("dd_21_chestplate", () -> new Dd21Item.Chestplate());
	public static final RegistryObject<Item> B_129 = block(RtddModBlocks.B_129, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_130 = block(RtddModBlocks.B_130, null);
	public static final RegistryObject<Item> B_131 = block(RtddModBlocks.B_131, null);
	public static final RegistryObject<Item> B_136 = block(RtddModBlocks.B_136, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_135 = block(RtddModBlocks.B_135, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_137 = block(RtddModBlocks.B_137, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_138 = block(RtddModBlocks.B_138, null);
	public static final RegistryObject<Item> B_140 = REGISTRY.register("b_140", () -> new B140Item());
	public static final RegistryObject<Item> B_141 = block(RtddModBlocks.B_141, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_143 = block(RtddModBlocks.B_143, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_144 = block(RtddModBlocks.B_144, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_145 = block(RtddModBlocks.B_145, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_148 = block(RtddModBlocks.B_148, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> B_149 = block(RtddModBlocks.B_149, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_158 = block(RtddModBlocks.B_158, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_159 = block(RtddModBlocks.B_159, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_161 = REGISTRY.register("b_161", () -> new B161Item());
	public static final RegistryObject<Item> NPC_2_SPAWN_EGG = REGISTRY.register("npc_2_spawn_egg", () -> new ForgeSpawnEggItem(RtddModEntities.NPC_2, -1, -1, new Item.Properties().tab(RtddModTabs.TAB_RTDD)));
	public static final RegistryObject<Item> NPC_1_SPAWN_EGG = REGISTRY.register("npc_1_spawn_egg", () -> new ForgeSpawnEggItem(RtddModEntities.NPC_1, -1, -1, new Item.Properties().tab(RtddModTabs.TAB_RTDD)));
	public static final RegistryObject<Item> NPC_3_SPAWN_EGG = REGISTRY.register("npc_3_spawn_egg", () -> new ForgeSpawnEggItem(RtddModEntities.NPC_3, -1, -1, new Item.Properties().tab(RtddModTabs.TAB_RTDD)));
	public static final RegistryObject<Item> MEATHOOKCOD_1 = block(RtddModBlocks.MEATHOOKCOD_1, null);
	public static final RegistryObject<Item> MEATHOOKCOD_2 = block(RtddModBlocks.MEATHOOKCOD_2, null);
	public static final RegistryObject<Item> FISH_1 = block(RtddModBlocks.FISH_1, null);
	public static final RegistryObject<Item> FISH_2 = block(RtddModBlocks.FISH_2, null);
	public static final RegistryObject<Item> SHEEP_1 = block(RtddModBlocks.SHEEP_1, null);
	public static final RegistryObject<Item> SHEEP = block(RtddModBlocks.SHEEP, null);
	public static final RegistryObject<Item> SHEEP_2 = block(RtddModBlocks.SHEEP_2, null);
	public static final RegistryObject<Item> SHEEP_3 = block(RtddModBlocks.SHEEP_3, null);
	public static final RegistryObject<Item> PIG = block(RtddModBlocks.PIG, null);
	public static final RegistryObject<Item> PIG_1 = block(RtddModBlocks.PIG_1, null);
	public static final RegistryObject<Item> PIG_2 = block(RtddModBlocks.PIG_2, null);
	public static final RegistryObject<Item> PIG_3 = block(RtddModBlocks.PIG_3, null);
	public static final RegistryObject<Item> PIG_0 = block(RtddModBlocks.PIG_0, null);
	public static final RegistryObject<Item> COW_0 = block(RtddModBlocks.COW_0, null);
	public static final RegistryObject<Item> COW_3 = block(RtddModBlocks.COW_3, null);
	public static final RegistryObject<Item> COW_2 = block(RtddModBlocks.COW_2, null);
	public static final RegistryObject<Item> COW_1 = block(RtddModBlocks.COW_1, null);
	public static final RegistryObject<Item> MEATHOOKCODDRY = block(RtddModBlocks.MEATHOOKCODDRY, null);
	public static final RegistryObject<Item> B_14 = block(RtddModBlocks.B_14, null);
	public static final RegistryObject<Item> B_16 = block(RtddModBlocks.B_16, null);
	public static final RegistryObject<Item> B_19 = block(RtddModBlocks.B_19, null);
	public static final RegistryObject<Item> B_12 = block(RtddModBlocks.B_12, null);
	public static final RegistryObject<Item> B_22 = block(RtddModBlocks.B_22, null);
	public static final RegistryObject<Item> B_24 = block(RtddModBlocks.B_24, null);
	public static final RegistryObject<Item> B_3 = block(RtddModBlocks.B_3, null);
	public static final RegistryObject<Item> B_26 = block(RtddModBlocks.B_26, null);
	public static final RegistryObject<Item> B_30 = block(RtddModBlocks.B_30, null);
	public static final RegistryObject<Item> B_39 = block(RtddModBlocks.B_39, null);
	public static final RegistryObject<Item> B_41 = block(RtddModBlocks.B_41, null);
	public static final RegistryObject<Item> B_42 = block(RtddModBlocks.B_42, null);
	public static final RegistryObject<Item> B_43 = block(RtddModBlocks.B_43, null);
	public static final RegistryObject<Item> B_44 = block(RtddModBlocks.B_44, null);
	public static final RegistryObject<Item> B_45 = block(RtddModBlocks.B_45, null);
	public static final RegistryObject<Item> D_5 = block(RtddModBlocks.D_5, null);
	public static final RegistryObject<Item> D_6 = block(RtddModBlocks.D_6, null);
	public static final RegistryObject<Item> MUG = REGISTRY.register("mug", () -> new MugItem());
	public static final RegistryObject<Item> B_49 = block(RtddModBlocks.B_49, null);
	public static final RegistryObject<Item> B_50 = block(RtddModBlocks.B_50, null);
	public static final RegistryObject<Item> B_55 = block(RtddModBlocks.B_55, null);
	public static final RegistryObject<Item> B_56 = block(RtddModBlocks.B_56, null);
	public static final RegistryObject<Item> B_58 = block(RtddModBlocks.B_58, null);
	public static final RegistryObject<Item> B_65 = block(RtddModBlocks.B_65, null);
	public static final RegistryObject<Item> B_66 = block(RtddModBlocks.B_66, null);
	public static final RegistryObject<Item> B_67 = block(RtddModBlocks.B_67, null);
	public static final RegistryObject<Item> B_68 = block(RtddModBlocks.B_68, null);
	public static final RegistryObject<Item> B_69 = block(RtddModBlocks.B_69, null);
	public static final RegistryObject<Item> B_70 = block(RtddModBlocks.B_70, null);
	public static final RegistryObject<Item> B_71 = block(RtddModBlocks.B_71, null);
	public static final RegistryObject<Item> B_72 = block(RtddModBlocks.B_72, null);
	public static final RegistryObject<Item> B_73 = block(RtddModBlocks.B_73, null);
	public static final RegistryObject<Item> B_74 = block(RtddModBlocks.B_74, null);
	public static final RegistryObject<Item> B_75 = block(RtddModBlocks.B_75, null);
	public static final RegistryObject<Item> B_76 = block(RtddModBlocks.B_76, null);
	public static final RegistryObject<Item> B_81 = block(RtddModBlocks.B_81, null);
	public static final RegistryObject<Item> B_82 = block(RtddModBlocks.B_82, null);
	public static final RegistryObject<Item> B_83 = block(RtddModBlocks.B_83, null);
	public static final RegistryObject<Item> B_84 = block(RtddModBlocks.B_84, null);
	public static final RegistryObject<Item> B_85 = block(RtddModBlocks.B_85, null);
	public static final RegistryObject<Item> B_89 = block(RtddModBlocks.B_89, null);
	public static final RegistryObject<Item> B_90 = block(RtddModBlocks.B_90, null);
	public static final RegistryObject<Item> B_91 = block(RtddModBlocks.B_91, null);
	public static final RegistryObject<Item> B_92 = block(RtddModBlocks.B_92, null);
	public static final RegistryObject<Item> B_93 = block(RtddModBlocks.B_93, null);
	public static final RegistryObject<Item> B_94 = block(RtddModBlocks.B_94, null);
	public static final RegistryObject<Item> B_95 = block(RtddModBlocks.B_95, null);
	public static final RegistryObject<Item> B_96 = block(RtddModBlocks.B_96, null);
	public static final RegistryObject<Item> B_97 = block(RtddModBlocks.B_97, null);
	public static final RegistryObject<Item> B_98 = block(RtddModBlocks.B_98, null);
	public static final RegistryObject<Item> BB_103 = block(RtddModBlocks.BB_103, null);
	public static final RegistryObject<Item> B_109 = block(RtddModBlocks.B_109, null);
	public static final RegistryObject<Item> B_114 = block(RtddModBlocks.B_114, null);
	public static final RegistryObject<Item> B_115 = block(RtddModBlocks.B_115, null);
	public static final RegistryObject<Item> B_116 = block(RtddModBlocks.B_116, null);
	public static final RegistryObject<Item> B_117 = block(RtddModBlocks.B_117, null);
	public static final RegistryObject<Item> B_118 = block(RtddModBlocks.B_118, null);
	public static final RegistryObject<Item> B_126 = block(RtddModBlocks.B_126, null);
	public static final RegistryObject<Item> B_132 = block(RtddModBlocks.B_132, null);
	public static final RegistryObject<Item> B_133 = block(RtddModBlocks.B_133, null);
	public static final RegistryObject<Item> B_134 = block(RtddModBlocks.B_134, null);
	public static final RegistryObject<Item> B_139 = block(RtddModBlocks.B_139, null);
	public static final RegistryObject<Item> B_142 = block(RtddModBlocks.B_142, null);
	public static final RegistryObject<Item> B_147 = block(RtddModBlocks.B_147, null);
	public static final RegistryObject<Item> B_150 = block(RtddModBlocks.B_150, null);
	public static final RegistryObject<Item> B_160 = block(RtddModBlocks.B_160, null);
	public static final RegistryObject<Item> B_166 = block(RtddModBlocks.B_166, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_167 = block(RtddModBlocks.B_167, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_168 = block(RtddModBlocks.B_168, null);
	public static final RegistryObject<Item> B_169 = block(RtddModBlocks.B_169, null);
	public static final RegistryObject<Item> B_170 = block(RtddModBlocks.B_170, null);
	public static final RegistryObject<Item> B_172 = block(RtddModBlocks.B_172, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_171 = block(RtddModBlocks.B_171, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_173 = block(RtddModBlocks.B_173, null);
	public static final RegistryObject<Item> B_176 = block(RtddModBlocks.B_176, null);
	public static final RegistryObject<Item> B_179 = block(RtddModBlocks.B_179, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> B_180 = block(RtddModBlocks.B_180, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_16 = block(RtddModBlocks.D_16, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_17 = block(RtddModBlocks.D_17, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_18 = block(RtddModBlocks.D_18, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_19 = block(RtddModBlocks.D_19, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_20 = block(RtddModBlocks.D_20, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_21 = block(RtddModBlocks.D_21, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_22 = block(RtddModBlocks.D_22, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_23 = block(RtddModBlocks.D_23, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_24 = block(RtddModBlocks.D_24, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_25 = block(RtddModBlocks.D_25, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_26 = block(RtddModBlocks.D_26, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_27 = block(RtddModBlocks.D_27, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_29 = block(RtddModBlocks.D_29, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> A_14 = block(RtddModBlocks.A_14, null);
	public static final RegistryObject<Item> A_16 = block(RtddModBlocks.A_16, null);
	public static final RegistryObject<Item> A_17 = block(RtddModBlocks.A_17, null);
	public static final RegistryObject<Item> A_21 = block(RtddModBlocks.A_21, null);
	public static final RegistryObject<Item> D_30 = block(RtddModBlocks.D_30, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_31 = block(RtddModBlocks.D_31, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_32 = block(RtddModBlocks.D_32, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_33 = block(RtddModBlocks.D_33, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_34 = block(RtddModBlocks.D_34, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_35 = block(RtddModBlocks.D_35, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_36 = block(RtddModBlocks.D_36, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_37 = block(RtddModBlocks.D_37, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_38 = block(RtddModBlocks.D_38, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_39 = block(RtddModBlocks.D_39, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_41 = block(RtddModBlocks.D_41, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_40 = block(RtddModBlocks.D_40, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_42 = block(RtddModBlocks.D_42, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_43 = block(RtddModBlocks.D_43, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_45 = block(RtddModBlocks.D_45, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_44 = block(RtddModBlocks.D_44, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_46 = block(RtddModBlocks.D_46, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_47 = block(RtddModBlocks.D_47, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_48 = block(RtddModBlocks.D_48, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_49 = block(RtddModBlocks.D_49, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_50 = block(RtddModBlocks.D_50, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_51 = block(RtddModBlocks.D_51, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_52 = block(RtddModBlocks.D_52, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_53 = block(RtddModBlocks.D_53, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_54 = block(RtddModBlocks.D_54, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_55 = block(RtddModBlocks.D_55, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_56 = block(RtddModBlocks.D_56, CreativeModeTab.TAB_BUILDING_BLOCKS);
	public static final RegistryObject<Item> D_57 = block(RtddModBlocks.D_57, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_58 = block(RtddModBlocks.D_58, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_59 = block(RtddModBlocks.D_59, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_60 = block(RtddModBlocks.D_60, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_61 = block(RtddModBlocks.D_61, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_62 = block(RtddModBlocks.D_62, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_63 = block(RtddModBlocks.D_63, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_64 = block(RtddModBlocks.D_64, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_65 = block(RtddModBlocks.D_65, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_66 = block(RtddModBlocks.D_66, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_67 = block(RtddModBlocks.D_67, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_68 = block(RtddModBlocks.D_68, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_69 = block(RtddModBlocks.D_69, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_70 = block(RtddModBlocks.D_70, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_80 = block(RtddModBlocks.D_80, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_71 = block(RtddModBlocks.D_71, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_72 = block(RtddModBlocks.D_72, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_73 = block(RtddModBlocks.D_73, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_74 = block(RtddModBlocks.D_74, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_75 = block(RtddModBlocks.D_75, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> D_76 = block(RtddModBlocks.D_76, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> D_77 = block(RtddModBlocks.D_77, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_181 = REGISTRY.register("b_181", () -> new B181Item());
	public static final RegistryObject<Item> B_183 = block(RtddModBlocks.B_183, null);
	public static final RegistryObject<Item> B_184 = block(RtddModBlocks.B_184, null);
	public static final RegistryObject<Item> B_185 = block(RtddModBlocks.B_185, null);
	public static final RegistryObject<Item> B_186 = block(RtddModBlocks.B_186, null);
	public static final RegistryObject<Item> B_187 = block(RtddModBlocks.B_187, null);
	public static final RegistryObject<Item> B_188 = block(RtddModBlocks.B_188, null);
	public static final RegistryObject<Item> B_189 = block(RtddModBlocks.B_189, null);
	public static final RegistryObject<Item> B_190 = block(RtddModBlocks.B_190, null);
	public static final RegistryObject<Item> B_191 = block(RtddModBlocks.B_191, null);
	public static final RegistryObject<Item> B_192 = block(RtddModBlocks.B_192, null);
	public static final RegistryObject<Item> B_193 = block(RtddModBlocks.B_193, null);
	public static final RegistryObject<Item> B_194 = block(RtddModBlocks.B_194, null);
	public static final RegistryObject<Item> B_195 = block(RtddModBlocks.B_195, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_196 = block(RtddModBlocks.B_196, null);
	public static final RegistryObject<Item> B_197 = block(RtddModBlocks.B_197, null);
	public static final RegistryObject<Item> B_198 = block(RtddModBlocks.B_198, null);
	public static final RegistryObject<Item> B_199 = block(RtddModBlocks.B_199, null);
	public static final RegistryObject<Item> B_200 = block(RtddModBlocks.B_200, null);
	public static final RegistryObject<Item> B_201 = block(RtddModBlocks.B_201, null);
	public static final RegistryObject<Item> B_203 = REGISTRY.register("b_203", () -> new B203Item());
	public static final RegistryObject<Item> B_205 = block(RtddModBlocks.B_205, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_206 = block(RtddModBlocks.B_206, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_207 = block(RtddModBlocks.B_207, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> D_78 = block(RtddModBlocks.D_78, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> B_208 = block(RtddModBlocks.B_208, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> B_209 = block(RtddModBlocks.B_209, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> B_210 = block(RtddModBlocks.B_210, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> B_211 = block(RtddModBlocks.B_211, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> D_79 = block(RtddModBlocks.D_79, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_81 = block(RtddModBlocks.D_81, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> D_82 = block(RtddModBlocks.D_82, RtddModTabs.TAB_RBULID);
	public static final RegistryObject<Item> HUOGUANG = REGISTRY.register("huoguang", () -> new HuoguangItem());
	public static final RegistryObject<Item> W_10 = REGISTRY.register("w_10", () -> new W10Item());
	public static final RegistryObject<Item> W_11 = REGISTRY.register("w_11", () -> new W11Item());
	public static final RegistryObject<Item> W_12 = REGISTRY.register("w_12", () -> new W12Item());
	public static final RegistryObject<Item> W_13 = REGISTRY.register("w_13", () -> new W13Item());
	public static final RegistryObject<Item> W_14 = REGISTRY.register("w_14", () -> new W14Item());
	public static final RegistryObject<Item> W_15 = REGISTRY.register("w_15", () -> new W15Item());
	public static final RegistryObject<Item> W_16 = REGISTRY.register("w_16", () -> new W16Item());
	public static final RegistryObject<Item> LUDENG = block(RtddModBlocks.LUDENG, null);
	public static final RegistryObject<Item> W_17 = REGISTRY.register("w_17", () -> new W17Item());
	public static final RegistryObject<Item> B_212 = block(RtddModBlocks.B_212, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> W_18 = REGISTRY.register("w_18", () -> new W18Item());
	public static final RegistryObject<Item> W_19 = REGISTRY.register("w_19", () -> new W19Item());
	public static final RegistryObject<Item> W_20 = REGISTRY.register("w_20", () -> new W20Item());
	public static final RegistryObject<Item> W_21 = REGISTRY.register("w_21", () -> new W21Item());
	public static final RegistryObject<Item> W_22 = REGISTRY.register("w_22", () -> new W22Item());
	public static final RegistryObject<Item> W_23 = block(RtddModBlocks.W_23, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> W_25 = block(RtddModBlocks.W_25, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> W_26 = block(RtddModBlocks.W_26, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> W_24 = block(RtddModBlocks.W_24, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> W_27 = REGISTRY.register("w_27", () -> new W27Item());
	public static final RegistryObject<Item> W_28 = REGISTRY.register("w_28", () -> new W28Item());
	public static final RegistryObject<Item> B_214 = block(RtddModBlocks.B_214, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_215 = block(RtddModBlocks.B_215, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_217 = block(RtddModBlocks.B_217, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> A_22 = REGISTRY.register("a_22", () -> new A22Item());
	public static final RegistryObject<Item> A_23 = REGISTRY.register("a_23", () -> new A23Item());
	public static final RegistryObject<Item> A_24 = REGISTRY.register("a_24", () -> new A24Item());
	public static final RegistryObject<Item> A_25 = REGISTRY.register("a_25", () -> new A25Item());
	public static final RegistryObject<Item> A_26 = REGISTRY.register("a_26", () -> new A26Item());
	public static final RegistryObject<Item> A_27 = REGISTRY.register("a_27", () -> new A27Item());
	public static final RegistryObject<Item> A_28 = REGISTRY.register("a_28", () -> new A28Item());
	public static final RegistryObject<Item> B_218 = block(RtddModBlocks.B_218, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> B_220 = block(RtddModBlocks.B_220, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> B_221 = block(RtddModBlocks.B_221, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> B_222 = block(RtddModBlocks.B_222, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> B_226 = block(RtddModBlocks.B_226, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> B_227 = block(RtddModBlocks.B_227, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> W_31 = block(RtddModBlocks.W_31, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> W_32 = block(RtddModBlocks.W_32, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> W_33 = block(RtddModBlocks.W_33, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> W_34 = block(RtddModBlocks.W_34, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> W_35 = block(RtddModBlocks.W_35, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> W_38 = block(RtddModBlocks.W_38, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> T_10 = REGISTRY.register("t_10", () -> new T10Item());
	public static final RegistryObject<Item> T_11 = REGISTRY.register("t_11", () -> new T11Item());
	public static final RegistryObject<Item> B_228 = block(RtddModBlocks.B_228, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_229 = block(RtddModBlocks.B_229, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_230_BUCKET = REGISTRY.register("b_230_bucket", () -> new B230Item());
	public static final RegistryObject<Item> GUIYUGOU_1 = block(RtddModBlocks.GUIYUGOU_1, null);
	public static final RegistryObject<Item> GUIYUGOU_2 = block(RtddModBlocks.GUIYUGOU_2, null);
	public static final RegistryObject<Item> GUIYUGOU_3 = block(RtddModBlocks.GUIYUGOU_3, null);
	public static final RegistryObject<Item> GUIYUGOU_4 = block(RtddModBlocks.GUIYUGOU_4, null);
	public static final RegistryObject<Item> B_232 = block(RtddModBlocks.B_232, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> B_233 = block(RtddModBlocks.B_233, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> HAIYANJIU = REGISTRY.register("haiyanjiu", () -> new HaiyanjiuItem());
	public static final RegistryObject<Item> ZILUOLANG = REGISTRY.register("ziluolang", () -> new ZiluolangItem());
	public static final RegistryObject<Item> FUTEJIA = REGISTRY.register("futejia", () -> new FutejiaItem());
	public static final RegistryObject<Item> B_234 = block(RtddModBlocks.B_234, null);
	public static final RegistryObject<Item> B_235 = block(RtddModBlocks.B_235, null);
	public static final RegistryObject<Item> B_236 = block(RtddModBlocks.B_236, null);
	public static final RegistryObject<Item> B_238 = block(RtddModBlocks.B_238, null);
	public static final RegistryObject<Item> B_239 = block(RtddModBlocks.B_239, null);
	public static final RegistryObject<Item> B_240 = block(RtddModBlocks.B_240, null);
	public static final RegistryObject<Item> B_238_T_1 = block(RtddModBlocks.B_238_T_1, null);
	public static final RegistryObject<Item> B_238_T_2 = block(RtddModBlocks.B_238_T_2, null);
	public static final RegistryObject<Item> B_238_T_3 = block(RtddModBlocks.B_238_T_3, null);
	public static final RegistryObject<Item> B_239_T_1 = block(RtddModBlocks.B_239_T_1, null);
	public static final RegistryObject<Item> B_239_T_2 = block(RtddModBlocks.B_239_T_2, null);
	public static final RegistryObject<Item> B_239_T_3 = block(RtddModBlocks.B_239_T_3, null);
	public static final RegistryObject<Item> B_240_T_1 = block(RtddModBlocks.B_240_T_1, null);
	public static final RegistryObject<Item> B_240_T_2 = block(RtddModBlocks.B_240_T_2, null);
	public static final RegistryObject<Item> B_240_T_3 = block(RtddModBlocks.B_240_T_3, null);
	public static final RegistryObject<Item> B_241 = block(RtddModBlocks.B_241, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_241A = block(RtddModBlocks.B_241A, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_242 = block(RtddModBlocks.B_242, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_242A = block(RtddModBlocks.B_242A, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_243 = block(RtddModBlocks.B_243, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_243A = block(RtddModBlocks.B_243A, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_244 = block(RtddModBlocks.B_244, null);
	public static final RegistryObject<Item> B_1 = block(RtddModBlocks.B_1, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> B_245 = block(RtddModBlocks.B_245, null);
	public static final RegistryObject<Item> B_247 = block(RtddModBlocks.B_247, null);
	public static final RegistryObject<Item> B_248 = block(RtddModBlocks.B_248, null);
	public static final RegistryObject<Item> B_249 = block(RtddModBlocks.B_249, null);
	public static final RegistryObject<Item> B_250 = block(RtddModBlocks.B_250, null);
	public static final RegistryObject<Item> B_246 = block(RtddModBlocks.B_246, null);
	public static final RegistryObject<Item> B_252 = block(RtddModBlocks.B_252, null);
	public static final RegistryObject<Item> B_253 = block(RtddModBlocks.B_253, null);
	public static final RegistryObject<Item> B_254 = block(RtddModBlocks.B_254, null);
	public static final RegistryObject<Item> B_255 = block(RtddModBlocks.B_255, null);
	public static final RegistryObject<Item> B_256 = block(RtddModBlocks.B_256, null);
	public static final RegistryObject<Item> B_258 = block(RtddModBlocks.B_258, null);
	public static final RegistryObject<Item> B_259 = block(RtddModBlocks.B_259, null);
	public static final RegistryObject<Item> B_260 = block(RtddModBlocks.B_260, null);
	public static final RegistryObject<Item> B_261 = block(RtddModBlocks.B_261, null);
	public static final RegistryObject<Item> B_262 = block(RtddModBlocks.B_262, null);
	public static final RegistryObject<Item> B_263 = REGISTRY.register("b_263", () -> new B263Item());
	public static final RegistryObject<Item> T_12 = REGISTRY.register("t_12", () -> new T12Item());
	public static final RegistryObject<Item> T_13 = REGISTRY.register("t_13", () -> new T13Item());
	public static final RegistryObject<Item> T_14 = REGISTRY.register("t_14", () -> new T14Item());
	public static final RegistryObject<Item> T_15 = REGISTRY.register("t_15", () -> new T15Item());
	public static final RegistryObject<Item> B_266 = block(RtddModBlocks.B_266, null);
	public static final RegistryObject<Item> B_267 = block(RtddModBlocks.B_267, null);
	public static final RegistryObject<Item> B_268 = block(RtddModBlocks.B_268, null);
	public static final RegistryObject<Item> B_269 = block(RtddModBlocks.B_269, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_270 = block(RtddModBlocks.B_270, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_272 = block(RtddModBlocks.B_272, null);
	public static final RegistryObject<Item> B_273 = block(RtddModBlocks.B_273, null);
	public static final RegistryObject<Item> B_274 = block(RtddModBlocks.B_274, null);
	public static final RegistryObject<Item> B_275 = block(RtddModBlocks.B_275, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_276 = block(RtddModBlocks.B_276, RtddModTabs.TAB_RTDD);
	public static final RegistryObject<Item> B_278 = block(RtddModBlocks.B_278, RtddModTabs.TAB_INDOORS);
	public static final RegistryObject<Item> B_279 = block(RtddModBlocks.B_279, null);
	public static final RegistryObject<Item> B_280 = block(RtddModBlocks.B_280, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> B_281 = block(RtddModBlocks.B_281, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> B_282 = block(RtddModBlocks.B_282, null);
	public static final RegistryObject<Item> B_283 = block(RtddModBlocks.B_283, null);
	public static final RegistryObject<Item> B_284 = block(RtddModBlocks.B_284, null);
	public static final RegistryObject<Item> B_285 = block(RtddModBlocks.B_285, RtddModTabs.TAB_RTOOL);
	public static final RegistryObject<Item> A_29 = block(RtddModBlocks.A_29, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> A_30 = block(RtddModBlocks.A_30, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> A_31 = block(RtddModBlocks.A_31, RtddModTabs.TAB_RFOOD);
	public static final RegistryObject<Item> DEADCOW = REGISTRY.register("deadcow", () -> new DeadcowItem());
	public static final RegistryObject<Item> DEADPIGG = REGISTRY.register("deadpigg", () -> new DeadpiggItem());
	public static final RegistryObject<Item> DEADSHEEP = REGISTRY.register("deadsheep", () -> new DeadsheepItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
