
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.rtdd.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.mcreator.rtdd.block.W38Block;
import net.mcreator.rtdd.block.W35Block;
import net.mcreator.rtdd.block.W34Block;
import net.mcreator.rtdd.block.W33Block;
import net.mcreator.rtdd.block.W32Block;
import net.mcreator.rtdd.block.W31Block;
import net.mcreator.rtdd.block.W26Block;
import net.mcreator.rtdd.block.W25Block;
import net.mcreator.rtdd.block.W24Block;
import net.mcreator.rtdd.block.W23Block;
import net.mcreator.rtdd.block.SheepBlock;
import net.mcreator.rtdd.block.Sheep3Block;
import net.mcreator.rtdd.block.Sheep2Block;
import net.mcreator.rtdd.block.Sheep1Block;
import net.mcreator.rtdd.block.PigBlock;
import net.mcreator.rtdd.block.Pig3Block;
import net.mcreator.rtdd.block.Pig2Block;
import net.mcreator.rtdd.block.Pig1Block;
import net.mcreator.rtdd.block.Pig0Block;
import net.mcreator.rtdd.block.MeathookcoddryBlock;
import net.mcreator.rtdd.block.Meathookcod2Block;
import net.mcreator.rtdd.block.Meathookcod1Block;
import net.mcreator.rtdd.block.MeathookBlock;
import net.mcreator.rtdd.block.LudengBlock;
import net.mcreator.rtdd.block.Guiyugou4Block;
import net.mcreator.rtdd.block.Guiyugou3Block;
import net.mcreator.rtdd.block.Guiyugou2Block;
import net.mcreator.rtdd.block.Guiyugou1Block;
import net.mcreator.rtdd.block.Fish2Block;
import net.mcreator.rtdd.block.Fish1Block;
import net.mcreator.rtdd.block.D9Block;
import net.mcreator.rtdd.block.D8Block;
import net.mcreator.rtdd.block.D82Block;
import net.mcreator.rtdd.block.D81Block;
import net.mcreator.rtdd.block.D80Block;
import net.mcreator.rtdd.block.D7Block;
import net.mcreator.rtdd.block.D79Block;
import net.mcreator.rtdd.block.D78Block;
import net.mcreator.rtdd.block.D77Block;
import net.mcreator.rtdd.block.D76Block;
import net.mcreator.rtdd.block.D75Block;
import net.mcreator.rtdd.block.D74Block;
import net.mcreator.rtdd.block.D73Block;
import net.mcreator.rtdd.block.D72Block;
import net.mcreator.rtdd.block.D71Block;
import net.mcreator.rtdd.block.D70Block;
import net.mcreator.rtdd.block.D6Block;
import net.mcreator.rtdd.block.D69Block;
import net.mcreator.rtdd.block.D68Block;
import net.mcreator.rtdd.block.D67Block;
import net.mcreator.rtdd.block.D66Block;
import net.mcreator.rtdd.block.D65Block;
import net.mcreator.rtdd.block.D64Block;
import net.mcreator.rtdd.block.D63Block;
import net.mcreator.rtdd.block.D62Block;
import net.mcreator.rtdd.block.D61Block;
import net.mcreator.rtdd.block.D60Block;
import net.mcreator.rtdd.block.D5Block;
import net.mcreator.rtdd.block.D59Block;
import net.mcreator.rtdd.block.D58Block;
import net.mcreator.rtdd.block.D57Block;
import net.mcreator.rtdd.block.D56Block;
import net.mcreator.rtdd.block.D55Block;
import net.mcreator.rtdd.block.D54Block;
import net.mcreator.rtdd.block.D53Block;
import net.mcreator.rtdd.block.D52Block;
import net.mcreator.rtdd.block.D51Block;
import net.mcreator.rtdd.block.D50Block;
import net.mcreator.rtdd.block.D4Block;
import net.mcreator.rtdd.block.D49Block;
import net.mcreator.rtdd.block.D48Block;
import net.mcreator.rtdd.block.D47Block;
import net.mcreator.rtdd.block.D46Block;
import net.mcreator.rtdd.block.D45Block;
import net.mcreator.rtdd.block.D44Block;
import net.mcreator.rtdd.block.D43Block;
import net.mcreator.rtdd.block.D42Block;
import net.mcreator.rtdd.block.D41Block;
import net.mcreator.rtdd.block.D40Block;
import net.mcreator.rtdd.block.D3Block;
import net.mcreator.rtdd.block.D39Block;
import net.mcreator.rtdd.block.D38Block;
import net.mcreator.rtdd.block.D37Block;
import net.mcreator.rtdd.block.D36Block;
import net.mcreator.rtdd.block.D35Block;
import net.mcreator.rtdd.block.D34Block;
import net.mcreator.rtdd.block.D33Block;
import net.mcreator.rtdd.block.D32Block;
import net.mcreator.rtdd.block.D31Block;
import net.mcreator.rtdd.block.D30Block;
import net.mcreator.rtdd.block.D2Block;
import net.mcreator.rtdd.block.D29Block;
import net.mcreator.rtdd.block.D27Block;
import net.mcreator.rtdd.block.D26Block;
import net.mcreator.rtdd.block.D25Block;
import net.mcreator.rtdd.block.D24Block;
import net.mcreator.rtdd.block.D23Block;
import net.mcreator.rtdd.block.D22Block;
import net.mcreator.rtdd.block.D21Block;
import net.mcreator.rtdd.block.D20Block;
import net.mcreator.rtdd.block.D1Block;
import net.mcreator.rtdd.block.D19Block;
import net.mcreator.rtdd.block.D18Block;
import net.mcreator.rtdd.block.D17Block;
import net.mcreator.rtdd.block.D16Block;
import net.mcreator.rtdd.block.D15Block;
import net.mcreator.rtdd.block.D14Block;
import net.mcreator.rtdd.block.D13Block;
import net.mcreator.rtdd.block.D12Block;
import net.mcreator.rtdd.block.D11Block;
import net.mcreator.rtdd.block.D10Block;
import net.mcreator.rtdd.block.Cow3Block;
import net.mcreator.rtdd.block.Cow2Block;
import net.mcreator.rtdd.block.Cow1Block;
import net.mcreator.rtdd.block.Cow0Block;
import net.mcreator.rtdd.block.CartBlock;
import net.mcreator.rtdd.block.Bb103Block;
import net.mcreator.rtdd.block.B98Block;
import net.mcreator.rtdd.block.B97Block;
import net.mcreator.rtdd.block.B96Block;
import net.mcreator.rtdd.block.B95Block;
import net.mcreator.rtdd.block.B94Block;
import net.mcreator.rtdd.block.B93Block;
import net.mcreator.rtdd.block.B92Block;
import net.mcreator.rtdd.block.B91Block;
import net.mcreator.rtdd.block.B90Block;
import net.mcreator.rtdd.block.B89Block;
import net.mcreator.rtdd.block.B88Block;
import net.mcreator.rtdd.block.B87Block;
import net.mcreator.rtdd.block.B86Block;
import net.mcreator.rtdd.block.B85Block;
import net.mcreator.rtdd.block.B84Block;
import net.mcreator.rtdd.block.B83Block;
import net.mcreator.rtdd.block.B82Block;
import net.mcreator.rtdd.block.B81Block;
import net.mcreator.rtdd.block.B76Block;
import net.mcreator.rtdd.block.B75Block;
import net.mcreator.rtdd.block.B74Block;
import net.mcreator.rtdd.block.B73Block;
import net.mcreator.rtdd.block.B72Block;
import net.mcreator.rtdd.block.B71Block;
import net.mcreator.rtdd.block.B70Block;
import net.mcreator.rtdd.block.B6Block;
import net.mcreator.rtdd.block.B69Block;
import net.mcreator.rtdd.block.B68Block;
import net.mcreator.rtdd.block.B67Block;
import net.mcreator.rtdd.block.B66Block;
import net.mcreator.rtdd.block.B65Block;
import net.mcreator.rtdd.block.B64Block;
import net.mcreator.rtdd.block.B63Block;
import net.mcreator.rtdd.block.B62Block;
import net.mcreator.rtdd.block.B61Block;
import net.mcreator.rtdd.block.B60Block;
import net.mcreator.rtdd.block.B59Block;
import net.mcreator.rtdd.block.B58Block;
import net.mcreator.rtdd.block.B57Block;
import net.mcreator.rtdd.block.B56Block;
import net.mcreator.rtdd.block.B55Block;
import net.mcreator.rtdd.block.B54Block;
import net.mcreator.rtdd.block.B53Block;
import net.mcreator.rtdd.block.B52Block;
import net.mcreator.rtdd.block.B51Block;
import net.mcreator.rtdd.block.B50Block;
import net.mcreator.rtdd.block.B4Block;
import net.mcreator.rtdd.block.B49Block;
import net.mcreator.rtdd.block.B45Block;
import net.mcreator.rtdd.block.B44Block;
import net.mcreator.rtdd.block.B43Block;
import net.mcreator.rtdd.block.B42Block;
import net.mcreator.rtdd.block.B41Block;
import net.mcreator.rtdd.block.B40Block;
import net.mcreator.rtdd.block.B3Block;
import net.mcreator.rtdd.block.B39Block;
import net.mcreator.rtdd.block.B38Block;
import net.mcreator.rtdd.block.B37Block;
import net.mcreator.rtdd.block.B36Block;
import net.mcreator.rtdd.block.B35Block;
import net.mcreator.rtdd.block.B34Block;
import net.mcreator.rtdd.block.B33Block;
import net.mcreator.rtdd.block.B31Block;
import net.mcreator.rtdd.block.B30Block;
import net.mcreator.rtdd.block.B2Block;
import net.mcreator.rtdd.block.B29Block;
import net.mcreator.rtdd.block.B28Block;
import net.mcreator.rtdd.block.B285Block;
import net.mcreator.rtdd.block.B284Block;
import net.mcreator.rtdd.block.B283Block;
import net.mcreator.rtdd.block.B282Block;
import net.mcreator.rtdd.block.B281Block;
import net.mcreator.rtdd.block.B280Block;
import net.mcreator.rtdd.block.B27Block;
import net.mcreator.rtdd.block.B279Block;
import net.mcreator.rtdd.block.B278Block;
import net.mcreator.rtdd.block.B276Block;
import net.mcreator.rtdd.block.B275Block;
import net.mcreator.rtdd.block.B274Block;
import net.mcreator.rtdd.block.B273Block;
import net.mcreator.rtdd.block.B272Block;
import net.mcreator.rtdd.block.B270Block;
import net.mcreator.rtdd.block.B26Block;
import net.mcreator.rtdd.block.B269Block;
import net.mcreator.rtdd.block.B268Block;
import net.mcreator.rtdd.block.B267Block;
import net.mcreator.rtdd.block.B266Block;
import net.mcreator.rtdd.block.B262Block;
import net.mcreator.rtdd.block.B261Block;
import net.mcreator.rtdd.block.B260Block;
import net.mcreator.rtdd.block.B25Block;
import net.mcreator.rtdd.block.B259Block;
import net.mcreator.rtdd.block.B258Block;
import net.mcreator.rtdd.block.B256Block;
import net.mcreator.rtdd.block.B255Block;
import net.mcreator.rtdd.block.B254Block;
import net.mcreator.rtdd.block.B253Block;
import net.mcreator.rtdd.block.B252Block;
import net.mcreator.rtdd.block.B250Block;
import net.mcreator.rtdd.block.B24Block;
import net.mcreator.rtdd.block.B249Block;
import net.mcreator.rtdd.block.B248Block;
import net.mcreator.rtdd.block.B247Block;
import net.mcreator.rtdd.block.B246Block;
import net.mcreator.rtdd.block.B245Block;
import net.mcreator.rtdd.block.B244Block;
import net.mcreator.rtdd.block.B243aBlock;
import net.mcreator.rtdd.block.B243Block;
import net.mcreator.rtdd.block.B242aBlock;
import net.mcreator.rtdd.block.B242Block;
import net.mcreator.rtdd.block.B241aBlock;
import net.mcreator.rtdd.block.B241Block;
import net.mcreator.rtdd.block.B240T3Block;
import net.mcreator.rtdd.block.B240T2Block;
import net.mcreator.rtdd.block.B240T1Block;
import net.mcreator.rtdd.block.B240Block;
import net.mcreator.rtdd.block.B23Block;
import net.mcreator.rtdd.block.B239T3Block;
import net.mcreator.rtdd.block.B239T2Block;
import net.mcreator.rtdd.block.B239T1Block;
import net.mcreator.rtdd.block.B239Block;
import net.mcreator.rtdd.block.B238T3Block;
import net.mcreator.rtdd.block.B238T2Block;
import net.mcreator.rtdd.block.B238T1Block;
import net.mcreator.rtdd.block.B238Block;
import net.mcreator.rtdd.block.B236Block;
import net.mcreator.rtdd.block.B235Block;
import net.mcreator.rtdd.block.B234Block;
import net.mcreator.rtdd.block.B233Block;
import net.mcreator.rtdd.block.B232Block;
import net.mcreator.rtdd.block.B230Block;
import net.mcreator.rtdd.block.B22Block;
import net.mcreator.rtdd.block.B229Block;
import net.mcreator.rtdd.block.B228Block;
import net.mcreator.rtdd.block.B227Block;
import net.mcreator.rtdd.block.B226Block;
import net.mcreator.rtdd.block.B222Block;
import net.mcreator.rtdd.block.B221Block;
import net.mcreator.rtdd.block.B220Block;
import net.mcreator.rtdd.block.B218Block;
import net.mcreator.rtdd.block.B217Block;
import net.mcreator.rtdd.block.B215Block;
import net.mcreator.rtdd.block.B214Block;
import net.mcreator.rtdd.block.B212Block;
import net.mcreator.rtdd.block.B211Block;
import net.mcreator.rtdd.block.B210Block;
import net.mcreator.rtdd.block.B209Block;
import net.mcreator.rtdd.block.B208Block;
import net.mcreator.rtdd.block.B207Block;
import net.mcreator.rtdd.block.B206Block;
import net.mcreator.rtdd.block.B205Block;
import net.mcreator.rtdd.block.B201Block;
import net.mcreator.rtdd.block.B200Block;
import net.mcreator.rtdd.block.B1Block;
import net.mcreator.rtdd.block.B19Block;
import net.mcreator.rtdd.block.B199Block;
import net.mcreator.rtdd.block.B198Block;
import net.mcreator.rtdd.block.B197Block;
import net.mcreator.rtdd.block.B196Block;
import net.mcreator.rtdd.block.B195Block;
import net.mcreator.rtdd.block.B194Block;
import net.mcreator.rtdd.block.B193Block;
import net.mcreator.rtdd.block.B192Block;
import net.mcreator.rtdd.block.B191Block;
import net.mcreator.rtdd.block.B190Block;
import net.mcreator.rtdd.block.B189Block;
import net.mcreator.rtdd.block.B188Block;
import net.mcreator.rtdd.block.B187Block;
import net.mcreator.rtdd.block.B186Block;
import net.mcreator.rtdd.block.B185Block;
import net.mcreator.rtdd.block.B184Block;
import net.mcreator.rtdd.block.B183Block;
import net.mcreator.rtdd.block.B180Block;
import net.mcreator.rtdd.block.B179Block;
import net.mcreator.rtdd.block.B176Block;
import net.mcreator.rtdd.block.B173Block;
import net.mcreator.rtdd.block.B172Block;
import net.mcreator.rtdd.block.B171Block;
import net.mcreator.rtdd.block.B170Block;
import net.mcreator.rtdd.block.B16Block;
import net.mcreator.rtdd.block.B169Block;
import net.mcreator.rtdd.block.B168Block;
import net.mcreator.rtdd.block.B167Block;
import net.mcreator.rtdd.block.B166Block;
import net.mcreator.rtdd.block.B160Block;
import net.mcreator.rtdd.block.B15Block;
import net.mcreator.rtdd.block.B159Block;
import net.mcreator.rtdd.block.B158Block;
import net.mcreator.rtdd.block.B150Block;
import net.mcreator.rtdd.block.B14Block;
import net.mcreator.rtdd.block.B149Block;
import net.mcreator.rtdd.block.B148Block;
import net.mcreator.rtdd.block.B147Block;
import net.mcreator.rtdd.block.B145Block;
import net.mcreator.rtdd.block.B144Block;
import net.mcreator.rtdd.block.B143Block;
import net.mcreator.rtdd.block.B142Block;
import net.mcreator.rtdd.block.B141Block;
import net.mcreator.rtdd.block.B139Block;
import net.mcreator.rtdd.block.B138Block;
import net.mcreator.rtdd.block.B137Block;
import net.mcreator.rtdd.block.B136Block;
import net.mcreator.rtdd.block.B135Block;
import net.mcreator.rtdd.block.B134Block;
import net.mcreator.rtdd.block.B133Block;
import net.mcreator.rtdd.block.B132Block;
import net.mcreator.rtdd.block.B131Block;
import net.mcreator.rtdd.block.B130Block;
import net.mcreator.rtdd.block.B12Block;
import net.mcreator.rtdd.block.B129Block;
import net.mcreator.rtdd.block.B128Block;
import net.mcreator.rtdd.block.B127Block;
import net.mcreator.rtdd.block.B126Block;
import net.mcreator.rtdd.block.B125Block;
import net.mcreator.rtdd.block.B124Block;
import net.mcreator.rtdd.block.B121Block;
import net.mcreator.rtdd.block.B120Block;
import net.mcreator.rtdd.block.B118Block;
import net.mcreator.rtdd.block.B117Block;
import net.mcreator.rtdd.block.B116Block;
import net.mcreator.rtdd.block.B115Block;
import net.mcreator.rtdd.block.B114Block;
import net.mcreator.rtdd.block.B113Block;
import net.mcreator.rtdd.block.B112Block;
import net.mcreator.rtdd.block.B111Block;
import net.mcreator.rtdd.block.B110Block;
import net.mcreator.rtdd.block.B109Block;
import net.mcreator.rtdd.block.B108Block;
import net.mcreator.rtdd.block.B107Block;
import net.mcreator.rtdd.block.B103Block;
import net.mcreator.rtdd.block.B102Block;
import net.mcreator.rtdd.block.A31Block;
import net.mcreator.rtdd.block.A30Block;
import net.mcreator.rtdd.block.A29Block;
import net.mcreator.rtdd.block.A21Block;
import net.mcreator.rtdd.block.A17Block;
import net.mcreator.rtdd.block.A16Block;
import net.mcreator.rtdd.block.A14Block;
import net.mcreator.rtdd.RtddMod;

public class RtddModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, RtddMod.MODID);
	public static final RegistryObject<Block> MEATHOOK = REGISTRY.register("meathook", () -> new MeathookBlock());
	public static final RegistryObject<Block> CART = REGISTRY.register("cart", () -> new CartBlock());
	public static final RegistryObject<Block> B_2 = REGISTRY.register("b_2", () -> new B2Block());
	public static final RegistryObject<Block> B_4 = REGISTRY.register("b_4", () -> new B4Block());
	public static final RegistryObject<Block> B_6 = REGISTRY.register("b_6", () -> new B6Block());
	public static final RegistryObject<Block> B_15 = REGISTRY.register("b_15", () -> new B15Block());
	public static final RegistryObject<Block> B_23 = REGISTRY.register("b_23", () -> new B23Block());
	public static final RegistryObject<Block> B_25 = REGISTRY.register("b_25", () -> new B25Block());
	public static final RegistryObject<Block> B_27 = REGISTRY.register("b_27", () -> new B27Block());
	public static final RegistryObject<Block> B_28 = REGISTRY.register("b_28", () -> new B28Block());
	public static final RegistryObject<Block> B_29 = REGISTRY.register("b_29", () -> new B29Block());
	public static final RegistryObject<Block> B_31 = REGISTRY.register("b_31", () -> new B31Block());
	public static final RegistryObject<Block> B_33 = REGISTRY.register("b_33", () -> new B33Block());
	public static final RegistryObject<Block> B_34 = REGISTRY.register("b_34", () -> new B34Block());
	public static final RegistryObject<Block> B_35 = REGISTRY.register("b_35", () -> new B35Block());
	public static final RegistryObject<Block> B_36 = REGISTRY.register("b_36", () -> new B36Block());
	public static final RegistryObject<Block> B_37 = REGISTRY.register("b_37", () -> new B37Block());
	public static final RegistryObject<Block> B_38 = REGISTRY.register("b_38", () -> new B38Block());
	public static final RegistryObject<Block> B_40 = REGISTRY.register("b_40", () -> new B40Block());
	public static final RegistryObject<Block> D_1 = REGISTRY.register("d_1", () -> new D1Block());
	public static final RegistryObject<Block> D_2 = REGISTRY.register("d_2", () -> new D2Block());
	public static final RegistryObject<Block> D_3 = REGISTRY.register("d_3", () -> new D3Block());
	public static final RegistryObject<Block> D_4 = REGISTRY.register("d_4", () -> new D4Block());
	public static final RegistryObject<Block> D_7 = REGISTRY.register("d_7", () -> new D7Block());
	public static final RegistryObject<Block> D_8 = REGISTRY.register("d_8", () -> new D8Block());
	public static final RegistryObject<Block> D_9 = REGISTRY.register("d_9", () -> new D9Block());
	public static final RegistryObject<Block> D_10 = REGISTRY.register("d_10", () -> new D10Block());
	public static final RegistryObject<Block> D_11 = REGISTRY.register("d_11", () -> new D11Block());
	public static final RegistryObject<Block> D_12 = REGISTRY.register("d_12", () -> new D12Block());
	public static final RegistryObject<Block> D_13 = REGISTRY.register("d_13", () -> new D13Block());
	public static final RegistryObject<Block> D_14 = REGISTRY.register("d_14", () -> new D14Block());
	public static final RegistryObject<Block> D_15 = REGISTRY.register("d_15", () -> new D15Block());
	public static final RegistryObject<Block> B_51 = REGISTRY.register("b_51", () -> new B51Block());
	public static final RegistryObject<Block> B_52 = REGISTRY.register("b_52", () -> new B52Block());
	public static final RegistryObject<Block> B_53 = REGISTRY.register("b_53", () -> new B53Block());
	public static final RegistryObject<Block> B_54 = REGISTRY.register("b_54", () -> new B54Block());
	public static final RegistryObject<Block> B_57 = REGISTRY.register("b_57", () -> new B57Block());
	public static final RegistryObject<Block> B_59 = REGISTRY.register("b_59", () -> new B59Block());
	public static final RegistryObject<Block> B_60 = REGISTRY.register("b_60", () -> new B60Block());
	public static final RegistryObject<Block> B_61 = REGISTRY.register("b_61", () -> new B61Block());
	public static final RegistryObject<Block> B_62 = REGISTRY.register("b_62", () -> new B62Block());
	public static final RegistryObject<Block> B_63 = REGISTRY.register("b_63", () -> new B63Block());
	public static final RegistryObject<Block> B_64 = REGISTRY.register("b_64", () -> new B64Block());
	public static final RegistryObject<Block> B_86 = REGISTRY.register("b_86", () -> new B86Block());
	public static final RegistryObject<Block> B_87 = REGISTRY.register("b_87", () -> new B87Block());
	public static final RegistryObject<Block> B_88 = REGISTRY.register("b_88", () -> new B88Block());
	public static final RegistryObject<Block> B_102 = REGISTRY.register("b_102", () -> new B102Block());
	public static final RegistryObject<Block> B_103 = REGISTRY.register("b_103", () -> new B103Block());
	public static final RegistryObject<Block> B_107 = REGISTRY.register("b_107", () -> new B107Block());
	public static final RegistryObject<Block> B_108 = REGISTRY.register("b_108", () -> new B108Block());
	public static final RegistryObject<Block> B_110 = REGISTRY.register("b_110", () -> new B110Block());
	public static final RegistryObject<Block> B_111 = REGISTRY.register("b_111", () -> new B111Block());
	public static final RegistryObject<Block> B_112 = REGISTRY.register("b_112", () -> new B112Block());
	public static final RegistryObject<Block> B_113 = REGISTRY.register("b_113", () -> new B113Block());
	public static final RegistryObject<Block> B_120 = REGISTRY.register("b_120", () -> new B120Block());
	public static final RegistryObject<Block> B_121 = REGISTRY.register("b_121", () -> new B121Block());
	public static final RegistryObject<Block> B_124 = REGISTRY.register("b_124", () -> new B124Block());
	public static final RegistryObject<Block> B_125 = REGISTRY.register("b_125", () -> new B125Block());
	public static final RegistryObject<Block> B_127 = REGISTRY.register("b_127", () -> new B127Block());
	public static final RegistryObject<Block> B_128 = REGISTRY.register("b_128", () -> new B128Block());
	public static final RegistryObject<Block> B_129 = REGISTRY.register("b_129", () -> new B129Block());
	public static final RegistryObject<Block> B_130 = REGISTRY.register("b_130", () -> new B130Block());
	public static final RegistryObject<Block> B_131 = REGISTRY.register("b_131", () -> new B131Block());
	public static final RegistryObject<Block> B_136 = REGISTRY.register("b_136", () -> new B136Block());
	public static final RegistryObject<Block> B_135 = REGISTRY.register("b_135", () -> new B135Block());
	public static final RegistryObject<Block> B_137 = REGISTRY.register("b_137", () -> new B137Block());
	public static final RegistryObject<Block> B_138 = REGISTRY.register("b_138", () -> new B138Block());
	public static final RegistryObject<Block> B_141 = REGISTRY.register("b_141", () -> new B141Block());
	public static final RegistryObject<Block> B_143 = REGISTRY.register("b_143", () -> new B143Block());
	public static final RegistryObject<Block> B_144 = REGISTRY.register("b_144", () -> new B144Block());
	public static final RegistryObject<Block> B_145 = REGISTRY.register("b_145", () -> new B145Block());
	public static final RegistryObject<Block> B_148 = REGISTRY.register("b_148", () -> new B148Block());
	public static final RegistryObject<Block> B_149 = REGISTRY.register("b_149", () -> new B149Block());
	public static final RegistryObject<Block> B_158 = REGISTRY.register("b_158", () -> new B158Block());
	public static final RegistryObject<Block> B_159 = REGISTRY.register("b_159", () -> new B159Block());
	public static final RegistryObject<Block> MEATHOOKCOD_1 = REGISTRY.register("meathookcod_1", () -> new Meathookcod1Block());
	public static final RegistryObject<Block> MEATHOOKCOD_2 = REGISTRY.register("meathookcod_2", () -> new Meathookcod2Block());
	public static final RegistryObject<Block> FISH_1 = REGISTRY.register("fish_1", () -> new Fish1Block());
	public static final RegistryObject<Block> FISH_2 = REGISTRY.register("fish_2", () -> new Fish2Block());
	public static final RegistryObject<Block> SHEEP_1 = REGISTRY.register("sheep_1", () -> new Sheep1Block());
	public static final RegistryObject<Block> SHEEP = REGISTRY.register("sheep", () -> new SheepBlock());
	public static final RegistryObject<Block> SHEEP_2 = REGISTRY.register("sheep_2", () -> new Sheep2Block());
	public static final RegistryObject<Block> SHEEP_3 = REGISTRY.register("sheep_3", () -> new Sheep3Block());
	public static final RegistryObject<Block> PIG = REGISTRY.register("pig", () -> new PigBlock());
	public static final RegistryObject<Block> PIG_1 = REGISTRY.register("pig_1", () -> new Pig1Block());
	public static final RegistryObject<Block> PIG_2 = REGISTRY.register("pig_2", () -> new Pig2Block());
	public static final RegistryObject<Block> PIG_3 = REGISTRY.register("pig_3", () -> new Pig3Block());
	public static final RegistryObject<Block> PIG_0 = REGISTRY.register("pig_0", () -> new Pig0Block());
	public static final RegistryObject<Block> COW_0 = REGISTRY.register("cow_0", () -> new Cow0Block());
	public static final RegistryObject<Block> COW_3 = REGISTRY.register("cow_3", () -> new Cow3Block());
	public static final RegistryObject<Block> COW_2 = REGISTRY.register("cow_2", () -> new Cow2Block());
	public static final RegistryObject<Block> COW_1 = REGISTRY.register("cow_1", () -> new Cow1Block());
	public static final RegistryObject<Block> MEATHOOKCODDRY = REGISTRY.register("meathookcoddry", () -> new MeathookcoddryBlock());
	public static final RegistryObject<Block> B_14 = REGISTRY.register("b_14", () -> new B14Block());
	public static final RegistryObject<Block> B_16 = REGISTRY.register("b_16", () -> new B16Block());
	public static final RegistryObject<Block> B_19 = REGISTRY.register("b_19", () -> new B19Block());
	public static final RegistryObject<Block> B_12 = REGISTRY.register("b_12", () -> new B12Block());
	public static final RegistryObject<Block> B_22 = REGISTRY.register("b_22", () -> new B22Block());
	public static final RegistryObject<Block> B_24 = REGISTRY.register("b_24", () -> new B24Block());
	public static final RegistryObject<Block> B_3 = REGISTRY.register("b_3", () -> new B3Block());
	public static final RegistryObject<Block> B_26 = REGISTRY.register("b_26", () -> new B26Block());
	public static final RegistryObject<Block> B_30 = REGISTRY.register("b_30", () -> new B30Block());
	public static final RegistryObject<Block> B_39 = REGISTRY.register("b_39", () -> new B39Block());
	public static final RegistryObject<Block> B_41 = REGISTRY.register("b_41", () -> new B41Block());
	public static final RegistryObject<Block> B_42 = REGISTRY.register("b_42", () -> new B42Block());
	public static final RegistryObject<Block> B_43 = REGISTRY.register("b_43", () -> new B43Block());
	public static final RegistryObject<Block> B_44 = REGISTRY.register("b_44", () -> new B44Block());
	public static final RegistryObject<Block> B_45 = REGISTRY.register("b_45", () -> new B45Block());
	public static final RegistryObject<Block> D_5 = REGISTRY.register("d_5", () -> new D5Block());
	public static final RegistryObject<Block> D_6 = REGISTRY.register("d_6", () -> new D6Block());
	public static final RegistryObject<Block> B_49 = REGISTRY.register("b_49", () -> new B49Block());
	public static final RegistryObject<Block> B_50 = REGISTRY.register("b_50", () -> new B50Block());
	public static final RegistryObject<Block> B_55 = REGISTRY.register("b_55", () -> new B55Block());
	public static final RegistryObject<Block> B_56 = REGISTRY.register("b_56", () -> new B56Block());
	public static final RegistryObject<Block> B_58 = REGISTRY.register("b_58", () -> new B58Block());
	public static final RegistryObject<Block> B_65 = REGISTRY.register("b_65", () -> new B65Block());
	public static final RegistryObject<Block> B_66 = REGISTRY.register("b_66", () -> new B66Block());
	public static final RegistryObject<Block> B_67 = REGISTRY.register("b_67", () -> new B67Block());
	public static final RegistryObject<Block> B_68 = REGISTRY.register("b_68", () -> new B68Block());
	public static final RegistryObject<Block> B_69 = REGISTRY.register("b_69", () -> new B69Block());
	public static final RegistryObject<Block> B_70 = REGISTRY.register("b_70", () -> new B70Block());
	public static final RegistryObject<Block> B_71 = REGISTRY.register("b_71", () -> new B71Block());
	public static final RegistryObject<Block> B_72 = REGISTRY.register("b_72", () -> new B72Block());
	public static final RegistryObject<Block> B_73 = REGISTRY.register("b_73", () -> new B73Block());
	public static final RegistryObject<Block> B_74 = REGISTRY.register("b_74", () -> new B74Block());
	public static final RegistryObject<Block> B_75 = REGISTRY.register("b_75", () -> new B75Block());
	public static final RegistryObject<Block> B_76 = REGISTRY.register("b_76", () -> new B76Block());
	public static final RegistryObject<Block> B_81 = REGISTRY.register("b_81", () -> new B81Block());
	public static final RegistryObject<Block> B_82 = REGISTRY.register("b_82", () -> new B82Block());
	public static final RegistryObject<Block> B_83 = REGISTRY.register("b_83", () -> new B83Block());
	public static final RegistryObject<Block> B_84 = REGISTRY.register("b_84", () -> new B84Block());
	public static final RegistryObject<Block> B_85 = REGISTRY.register("b_85", () -> new B85Block());
	public static final RegistryObject<Block> B_89 = REGISTRY.register("b_89", () -> new B89Block());
	public static final RegistryObject<Block> B_90 = REGISTRY.register("b_90", () -> new B90Block());
	public static final RegistryObject<Block> B_91 = REGISTRY.register("b_91", () -> new B91Block());
	public static final RegistryObject<Block> B_92 = REGISTRY.register("b_92", () -> new B92Block());
	public static final RegistryObject<Block> B_93 = REGISTRY.register("b_93", () -> new B93Block());
	public static final RegistryObject<Block> B_94 = REGISTRY.register("b_94", () -> new B94Block());
	public static final RegistryObject<Block> B_95 = REGISTRY.register("b_95", () -> new B95Block());
	public static final RegistryObject<Block> B_96 = REGISTRY.register("b_96", () -> new B96Block());
	public static final RegistryObject<Block> B_97 = REGISTRY.register("b_97", () -> new B97Block());
	public static final RegistryObject<Block> B_98 = REGISTRY.register("b_98", () -> new B98Block());
	public static final RegistryObject<Block> BB_103 = REGISTRY.register("bb_103", () -> new Bb103Block());
	public static final RegistryObject<Block> B_109 = REGISTRY.register("b_109", () -> new B109Block());
	public static final RegistryObject<Block> B_114 = REGISTRY.register("b_114", () -> new B114Block());
	public static final RegistryObject<Block> B_115 = REGISTRY.register("b_115", () -> new B115Block());
	public static final RegistryObject<Block> B_116 = REGISTRY.register("b_116", () -> new B116Block());
	public static final RegistryObject<Block> B_117 = REGISTRY.register("b_117", () -> new B117Block());
	public static final RegistryObject<Block> B_118 = REGISTRY.register("b_118", () -> new B118Block());
	public static final RegistryObject<Block> B_126 = REGISTRY.register("b_126", () -> new B126Block());
	public static final RegistryObject<Block> B_132 = REGISTRY.register("b_132", () -> new B132Block());
	public static final RegistryObject<Block> B_133 = REGISTRY.register("b_133", () -> new B133Block());
	public static final RegistryObject<Block> B_134 = REGISTRY.register("b_134", () -> new B134Block());
	public static final RegistryObject<Block> B_139 = REGISTRY.register("b_139", () -> new B139Block());
	public static final RegistryObject<Block> B_142 = REGISTRY.register("b_142", () -> new B142Block());
	public static final RegistryObject<Block> B_147 = REGISTRY.register("b_147", () -> new B147Block());
	public static final RegistryObject<Block> B_150 = REGISTRY.register("b_150", () -> new B150Block());
	public static final RegistryObject<Block> B_160 = REGISTRY.register("b_160", () -> new B160Block());
	public static final RegistryObject<Block> B_166 = REGISTRY.register("b_166", () -> new B166Block());
	public static final RegistryObject<Block> B_167 = REGISTRY.register("b_167", () -> new B167Block());
	public static final RegistryObject<Block> B_168 = REGISTRY.register("b_168", () -> new B168Block());
	public static final RegistryObject<Block> B_169 = REGISTRY.register("b_169", () -> new B169Block());
	public static final RegistryObject<Block> B_170 = REGISTRY.register("b_170", () -> new B170Block());
	public static final RegistryObject<Block> B_172 = REGISTRY.register("b_172", () -> new B172Block());
	public static final RegistryObject<Block> B_171 = REGISTRY.register("b_171", () -> new B171Block());
	public static final RegistryObject<Block> B_173 = REGISTRY.register("b_173", () -> new B173Block());
	public static final RegistryObject<Block> B_176 = REGISTRY.register("b_176", () -> new B176Block());
	public static final RegistryObject<Block> B_179 = REGISTRY.register("b_179", () -> new B179Block());
	public static final RegistryObject<Block> B_180 = REGISTRY.register("b_180", () -> new B180Block());
	public static final RegistryObject<Block> D_16 = REGISTRY.register("d_16", () -> new D16Block());
	public static final RegistryObject<Block> D_17 = REGISTRY.register("d_17", () -> new D17Block());
	public static final RegistryObject<Block> D_18 = REGISTRY.register("d_18", () -> new D18Block());
	public static final RegistryObject<Block> D_19 = REGISTRY.register("d_19", () -> new D19Block());
	public static final RegistryObject<Block> D_20 = REGISTRY.register("d_20", () -> new D20Block());
	public static final RegistryObject<Block> D_21 = REGISTRY.register("d_21", () -> new D21Block());
	public static final RegistryObject<Block> D_22 = REGISTRY.register("d_22", () -> new D22Block());
	public static final RegistryObject<Block> D_23 = REGISTRY.register("d_23", () -> new D23Block());
	public static final RegistryObject<Block> D_24 = REGISTRY.register("d_24", () -> new D24Block());
	public static final RegistryObject<Block> D_25 = REGISTRY.register("d_25", () -> new D25Block());
	public static final RegistryObject<Block> D_26 = REGISTRY.register("d_26", () -> new D26Block());
	public static final RegistryObject<Block> D_27 = REGISTRY.register("d_27", () -> new D27Block());
	public static final RegistryObject<Block> D_29 = REGISTRY.register("d_29", () -> new D29Block());
	public static final RegistryObject<Block> A_14 = REGISTRY.register("a_14", () -> new A14Block());
	public static final RegistryObject<Block> A_16 = REGISTRY.register("a_16", () -> new A16Block());
	public static final RegistryObject<Block> A_17 = REGISTRY.register("a_17", () -> new A17Block());
	public static final RegistryObject<Block> A_21 = REGISTRY.register("a_21", () -> new A21Block());
	public static final RegistryObject<Block> D_30 = REGISTRY.register("d_30", () -> new D30Block());
	public static final RegistryObject<Block> D_31 = REGISTRY.register("d_31", () -> new D31Block());
	public static final RegistryObject<Block> D_32 = REGISTRY.register("d_32", () -> new D32Block());
	public static final RegistryObject<Block> D_33 = REGISTRY.register("d_33", () -> new D33Block());
	public static final RegistryObject<Block> D_34 = REGISTRY.register("d_34", () -> new D34Block());
	public static final RegistryObject<Block> D_35 = REGISTRY.register("d_35", () -> new D35Block());
	public static final RegistryObject<Block> D_36 = REGISTRY.register("d_36", () -> new D36Block());
	public static final RegistryObject<Block> D_37 = REGISTRY.register("d_37", () -> new D37Block());
	public static final RegistryObject<Block> D_38 = REGISTRY.register("d_38", () -> new D38Block());
	public static final RegistryObject<Block> D_39 = REGISTRY.register("d_39", () -> new D39Block());
	public static final RegistryObject<Block> D_41 = REGISTRY.register("d_41", () -> new D41Block());
	public static final RegistryObject<Block> D_40 = REGISTRY.register("d_40", () -> new D40Block());
	public static final RegistryObject<Block> D_42 = REGISTRY.register("d_42", () -> new D42Block());
	public static final RegistryObject<Block> D_43 = REGISTRY.register("d_43", () -> new D43Block());
	public static final RegistryObject<Block> D_45 = REGISTRY.register("d_45", () -> new D45Block());
	public static final RegistryObject<Block> D_44 = REGISTRY.register("d_44", () -> new D44Block());
	public static final RegistryObject<Block> D_46 = REGISTRY.register("d_46", () -> new D46Block());
	public static final RegistryObject<Block> D_47 = REGISTRY.register("d_47", () -> new D47Block());
	public static final RegistryObject<Block> D_48 = REGISTRY.register("d_48", () -> new D48Block());
	public static final RegistryObject<Block> D_49 = REGISTRY.register("d_49", () -> new D49Block());
	public static final RegistryObject<Block> D_50 = REGISTRY.register("d_50", () -> new D50Block());
	public static final RegistryObject<Block> D_51 = REGISTRY.register("d_51", () -> new D51Block());
	public static final RegistryObject<Block> D_52 = REGISTRY.register("d_52", () -> new D52Block());
	public static final RegistryObject<Block> D_53 = REGISTRY.register("d_53", () -> new D53Block());
	public static final RegistryObject<Block> D_54 = REGISTRY.register("d_54", () -> new D54Block());
	public static final RegistryObject<Block> D_55 = REGISTRY.register("d_55", () -> new D55Block());
	public static final RegistryObject<Block> D_56 = REGISTRY.register("d_56", () -> new D56Block());
	public static final RegistryObject<Block> D_57 = REGISTRY.register("d_57", () -> new D57Block());
	public static final RegistryObject<Block> D_58 = REGISTRY.register("d_58", () -> new D58Block());
	public static final RegistryObject<Block> D_59 = REGISTRY.register("d_59", () -> new D59Block());
	public static final RegistryObject<Block> D_60 = REGISTRY.register("d_60", () -> new D60Block());
	public static final RegistryObject<Block> D_61 = REGISTRY.register("d_61", () -> new D61Block());
	public static final RegistryObject<Block> D_62 = REGISTRY.register("d_62", () -> new D62Block());
	public static final RegistryObject<Block> D_63 = REGISTRY.register("d_63", () -> new D63Block());
	public static final RegistryObject<Block> D_64 = REGISTRY.register("d_64", () -> new D64Block());
	public static final RegistryObject<Block> D_65 = REGISTRY.register("d_65", () -> new D65Block());
	public static final RegistryObject<Block> D_66 = REGISTRY.register("d_66", () -> new D66Block());
	public static final RegistryObject<Block> D_67 = REGISTRY.register("d_67", () -> new D67Block());
	public static final RegistryObject<Block> D_68 = REGISTRY.register("d_68", () -> new D68Block());
	public static final RegistryObject<Block> D_69 = REGISTRY.register("d_69", () -> new D69Block());
	public static final RegistryObject<Block> D_70 = REGISTRY.register("d_70", () -> new D70Block());
	public static final RegistryObject<Block> D_80 = REGISTRY.register("d_80", () -> new D80Block());
	public static final RegistryObject<Block> D_71 = REGISTRY.register("d_71", () -> new D71Block());
	public static final RegistryObject<Block> D_72 = REGISTRY.register("d_72", () -> new D72Block());
	public static final RegistryObject<Block> D_73 = REGISTRY.register("d_73", () -> new D73Block());
	public static final RegistryObject<Block> D_74 = REGISTRY.register("d_74", () -> new D74Block());
	public static final RegistryObject<Block> D_75 = REGISTRY.register("d_75", () -> new D75Block());
	public static final RegistryObject<Block> D_76 = REGISTRY.register("d_76", () -> new D76Block());
	public static final RegistryObject<Block> D_77 = REGISTRY.register("d_77", () -> new D77Block());
	public static final RegistryObject<Block> B_183 = REGISTRY.register("b_183", () -> new B183Block());
	public static final RegistryObject<Block> B_184 = REGISTRY.register("b_184", () -> new B184Block());
	public static final RegistryObject<Block> B_185 = REGISTRY.register("b_185", () -> new B185Block());
	public static final RegistryObject<Block> B_186 = REGISTRY.register("b_186", () -> new B186Block());
	public static final RegistryObject<Block> B_187 = REGISTRY.register("b_187", () -> new B187Block());
	public static final RegistryObject<Block> B_188 = REGISTRY.register("b_188", () -> new B188Block());
	public static final RegistryObject<Block> B_189 = REGISTRY.register("b_189", () -> new B189Block());
	public static final RegistryObject<Block> B_190 = REGISTRY.register("b_190", () -> new B190Block());
	public static final RegistryObject<Block> B_191 = REGISTRY.register("b_191", () -> new B191Block());
	public static final RegistryObject<Block> B_192 = REGISTRY.register("b_192", () -> new B192Block());
	public static final RegistryObject<Block> B_193 = REGISTRY.register("b_193", () -> new B193Block());
	public static final RegistryObject<Block> B_194 = REGISTRY.register("b_194", () -> new B194Block());
	public static final RegistryObject<Block> B_195 = REGISTRY.register("b_195", () -> new B195Block());
	public static final RegistryObject<Block> B_196 = REGISTRY.register("b_196", () -> new B196Block());
	public static final RegistryObject<Block> B_197 = REGISTRY.register("b_197", () -> new B197Block());
	public static final RegistryObject<Block> B_198 = REGISTRY.register("b_198", () -> new B198Block());
	public static final RegistryObject<Block> B_199 = REGISTRY.register("b_199", () -> new B199Block());
	public static final RegistryObject<Block> B_200 = REGISTRY.register("b_200", () -> new B200Block());
	public static final RegistryObject<Block> B_201 = REGISTRY.register("b_201", () -> new B201Block());
	public static final RegistryObject<Block> B_205 = REGISTRY.register("b_205", () -> new B205Block());
	public static final RegistryObject<Block> B_206 = REGISTRY.register("b_206", () -> new B206Block());
	public static final RegistryObject<Block> B_207 = REGISTRY.register("b_207", () -> new B207Block());
	public static final RegistryObject<Block> D_78 = REGISTRY.register("d_78", () -> new D78Block());
	public static final RegistryObject<Block> B_208 = REGISTRY.register("b_208", () -> new B208Block());
	public static final RegistryObject<Block> B_209 = REGISTRY.register("b_209", () -> new B209Block());
	public static final RegistryObject<Block> B_210 = REGISTRY.register("b_210", () -> new B210Block());
	public static final RegistryObject<Block> B_211 = REGISTRY.register("b_211", () -> new B211Block());
	public static final RegistryObject<Block> D_79 = REGISTRY.register("d_79", () -> new D79Block());
	public static final RegistryObject<Block> D_81 = REGISTRY.register("d_81", () -> new D81Block());
	public static final RegistryObject<Block> D_82 = REGISTRY.register("d_82", () -> new D82Block());
	public static final RegistryObject<Block> LUDENG = REGISTRY.register("ludeng", () -> new LudengBlock());
	public static final RegistryObject<Block> B_212 = REGISTRY.register("b_212", () -> new B212Block());
	public static final RegistryObject<Block> W_23 = REGISTRY.register("w_23", () -> new W23Block());
	public static final RegistryObject<Block> W_25 = REGISTRY.register("w_25", () -> new W25Block());
	public static final RegistryObject<Block> W_26 = REGISTRY.register("w_26", () -> new W26Block());
	public static final RegistryObject<Block> W_24 = REGISTRY.register("w_24", () -> new W24Block());
	public static final RegistryObject<Block> B_214 = REGISTRY.register("b_214", () -> new B214Block());
	public static final RegistryObject<Block> B_215 = REGISTRY.register("b_215", () -> new B215Block());
	public static final RegistryObject<Block> B_217 = REGISTRY.register("b_217", () -> new B217Block());
	public static final RegistryObject<Block> B_218 = REGISTRY.register("b_218", () -> new B218Block());
	public static final RegistryObject<Block> B_220 = REGISTRY.register("b_220", () -> new B220Block());
	public static final RegistryObject<Block> B_221 = REGISTRY.register("b_221", () -> new B221Block());
	public static final RegistryObject<Block> B_222 = REGISTRY.register("b_222", () -> new B222Block());
	public static final RegistryObject<Block> B_226 = REGISTRY.register("b_226", () -> new B226Block());
	public static final RegistryObject<Block> B_227 = REGISTRY.register("b_227", () -> new B227Block());
	public static final RegistryObject<Block> W_31 = REGISTRY.register("w_31", () -> new W31Block());
	public static final RegistryObject<Block> W_32 = REGISTRY.register("w_32", () -> new W32Block());
	public static final RegistryObject<Block> W_33 = REGISTRY.register("w_33", () -> new W33Block());
	public static final RegistryObject<Block> W_34 = REGISTRY.register("w_34", () -> new W34Block());
	public static final RegistryObject<Block> W_35 = REGISTRY.register("w_35", () -> new W35Block());
	public static final RegistryObject<Block> W_38 = REGISTRY.register("w_38", () -> new W38Block());
	public static final RegistryObject<Block> B_228 = REGISTRY.register("b_228", () -> new B228Block());
	public static final RegistryObject<Block> B_229 = REGISTRY.register("b_229", () -> new B229Block());
	public static final RegistryObject<Block> B_230 = REGISTRY.register("b_230", () -> new B230Block());
	public static final RegistryObject<Block> GUIYUGOU_1 = REGISTRY.register("guiyugou_1", () -> new Guiyugou1Block());
	public static final RegistryObject<Block> GUIYUGOU_2 = REGISTRY.register("guiyugou_2", () -> new Guiyugou2Block());
	public static final RegistryObject<Block> GUIYUGOU_3 = REGISTRY.register("guiyugou_3", () -> new Guiyugou3Block());
	public static final RegistryObject<Block> GUIYUGOU_4 = REGISTRY.register("guiyugou_4", () -> new Guiyugou4Block());
	public static final RegistryObject<Block> B_232 = REGISTRY.register("b_232", () -> new B232Block());
	public static final RegistryObject<Block> B_233 = REGISTRY.register("b_233", () -> new B233Block());
	public static final RegistryObject<Block> B_234 = REGISTRY.register("b_234", () -> new B234Block());
	public static final RegistryObject<Block> B_235 = REGISTRY.register("b_235", () -> new B235Block());
	public static final RegistryObject<Block> B_236 = REGISTRY.register("b_236", () -> new B236Block());
	public static final RegistryObject<Block> B_238 = REGISTRY.register("b_238", () -> new B238Block());
	public static final RegistryObject<Block> B_239 = REGISTRY.register("b_239", () -> new B239Block());
	public static final RegistryObject<Block> B_240 = REGISTRY.register("b_240", () -> new B240Block());
	public static final RegistryObject<Block> B_238_T_1 = REGISTRY.register("b_238_t_1", () -> new B238T1Block());
	public static final RegistryObject<Block> B_238_T_2 = REGISTRY.register("b_238_t_2", () -> new B238T2Block());
	public static final RegistryObject<Block> B_238_T_3 = REGISTRY.register("b_238_t_3", () -> new B238T3Block());
	public static final RegistryObject<Block> B_239_T_1 = REGISTRY.register("b_239_t_1", () -> new B239T1Block());
	public static final RegistryObject<Block> B_239_T_2 = REGISTRY.register("b_239_t_2", () -> new B239T2Block());
	public static final RegistryObject<Block> B_239_T_3 = REGISTRY.register("b_239_t_3", () -> new B239T3Block());
	public static final RegistryObject<Block> B_240_T_1 = REGISTRY.register("b_240_t_1", () -> new B240T1Block());
	public static final RegistryObject<Block> B_240_T_2 = REGISTRY.register("b_240_t_2", () -> new B240T2Block());
	public static final RegistryObject<Block> B_240_T_3 = REGISTRY.register("b_240_t_3", () -> new B240T3Block());
	public static final RegistryObject<Block> B_241 = REGISTRY.register("b_241", () -> new B241Block());
	public static final RegistryObject<Block> B_241A = REGISTRY.register("b_241a", () -> new B241aBlock());
	public static final RegistryObject<Block> B_242 = REGISTRY.register("b_242", () -> new B242Block());
	public static final RegistryObject<Block> B_242A = REGISTRY.register("b_242a", () -> new B242aBlock());
	public static final RegistryObject<Block> B_243 = REGISTRY.register("b_243", () -> new B243Block());
	public static final RegistryObject<Block> B_243A = REGISTRY.register("b_243a", () -> new B243aBlock());
	public static final RegistryObject<Block> B_244 = REGISTRY.register("b_244", () -> new B244Block());
	public static final RegistryObject<Block> B_1 = REGISTRY.register("b_1", () -> new B1Block());
	public static final RegistryObject<Block> B_245 = REGISTRY.register("b_245", () -> new B245Block());
	public static final RegistryObject<Block> B_247 = REGISTRY.register("b_247", () -> new B247Block());
	public static final RegistryObject<Block> B_248 = REGISTRY.register("b_248", () -> new B248Block());
	public static final RegistryObject<Block> B_249 = REGISTRY.register("b_249", () -> new B249Block());
	public static final RegistryObject<Block> B_250 = REGISTRY.register("b_250", () -> new B250Block());
	public static final RegistryObject<Block> B_246 = REGISTRY.register("b_246", () -> new B246Block());
	public static final RegistryObject<Block> B_252 = REGISTRY.register("b_252", () -> new B252Block());
	public static final RegistryObject<Block> B_253 = REGISTRY.register("b_253", () -> new B253Block());
	public static final RegistryObject<Block> B_254 = REGISTRY.register("b_254", () -> new B254Block());
	public static final RegistryObject<Block> B_255 = REGISTRY.register("b_255", () -> new B255Block());
	public static final RegistryObject<Block> B_256 = REGISTRY.register("b_256", () -> new B256Block());
	public static final RegistryObject<Block> B_258 = REGISTRY.register("b_258", () -> new B258Block());
	public static final RegistryObject<Block> B_259 = REGISTRY.register("b_259", () -> new B259Block());
	public static final RegistryObject<Block> B_260 = REGISTRY.register("b_260", () -> new B260Block());
	public static final RegistryObject<Block> B_261 = REGISTRY.register("b_261", () -> new B261Block());
	public static final RegistryObject<Block> B_262 = REGISTRY.register("b_262", () -> new B262Block());
	public static final RegistryObject<Block> B_266 = REGISTRY.register("b_266", () -> new B266Block());
	public static final RegistryObject<Block> B_267 = REGISTRY.register("b_267", () -> new B267Block());
	public static final RegistryObject<Block> B_268 = REGISTRY.register("b_268", () -> new B268Block());
	public static final RegistryObject<Block> B_269 = REGISTRY.register("b_269", () -> new B269Block());
	public static final RegistryObject<Block> B_270 = REGISTRY.register("b_270", () -> new B270Block());
	public static final RegistryObject<Block> B_272 = REGISTRY.register("b_272", () -> new B272Block());
	public static final RegistryObject<Block> B_273 = REGISTRY.register("b_273", () -> new B273Block());
	public static final RegistryObject<Block> B_274 = REGISTRY.register("b_274", () -> new B274Block());
	public static final RegistryObject<Block> B_275 = REGISTRY.register("b_275", () -> new B275Block());
	public static final RegistryObject<Block> B_276 = REGISTRY.register("b_276", () -> new B276Block());
	public static final RegistryObject<Block> B_278 = REGISTRY.register("b_278", () -> new B278Block());
	public static final RegistryObject<Block> B_279 = REGISTRY.register("b_279", () -> new B279Block());
	public static final RegistryObject<Block> B_280 = REGISTRY.register("b_280", () -> new B280Block());
	public static final RegistryObject<Block> B_281 = REGISTRY.register("b_281", () -> new B281Block());
	public static final RegistryObject<Block> B_282 = REGISTRY.register("b_282", () -> new B282Block());
	public static final RegistryObject<Block> B_283 = REGISTRY.register("b_283", () -> new B283Block());
	public static final RegistryObject<Block> B_284 = REGISTRY.register("b_284", () -> new B284Block());
	public static final RegistryObject<Block> B_285 = REGISTRY.register("b_285", () -> new B285Block());
	public static final RegistryObject<Block> A_29 = REGISTRY.register("a_29", () -> new A29Block());
	public static final RegistryObject<Block> A_30 = REGISTRY.register("a_30", () -> new A30Block());
	public static final RegistryObject<Block> A_31 = REGISTRY.register("a_31", () -> new A31Block());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void clientSetup(FMLClientSetupEvent event) {
			MeathookBlock.registerRenderLayer();
			CartBlock.registerRenderLayer();
			B2Block.registerRenderLayer();
			B4Block.registerRenderLayer();
			B6Block.registerRenderLayer();
			B15Block.registerRenderLayer();
			B23Block.registerRenderLayer();
			B25Block.registerRenderLayer();
			B27Block.registerRenderLayer();
			B28Block.registerRenderLayer();
			B29Block.registerRenderLayer();
			B31Block.registerRenderLayer();
			B33Block.registerRenderLayer();
			B34Block.registerRenderLayer();
			B35Block.registerRenderLayer();
			B36Block.registerRenderLayer();
			B37Block.registerRenderLayer();
			B38Block.registerRenderLayer();
			B40Block.registerRenderLayer();
			D1Block.registerRenderLayer();
			D2Block.registerRenderLayer();
			D3Block.registerRenderLayer();
			D4Block.registerRenderLayer();
			D7Block.registerRenderLayer();
			D8Block.registerRenderLayer();
			D9Block.registerRenderLayer();
			D10Block.registerRenderLayer();
			D11Block.registerRenderLayer();
			D12Block.registerRenderLayer();
			D13Block.registerRenderLayer();
			D14Block.registerRenderLayer();
			D15Block.registerRenderLayer();
			B51Block.registerRenderLayer();
			B52Block.registerRenderLayer();
			B53Block.registerRenderLayer();
			B54Block.registerRenderLayer();
			B57Block.registerRenderLayer();
			B59Block.registerRenderLayer();
			B60Block.registerRenderLayer();
			B61Block.registerRenderLayer();
			B62Block.registerRenderLayer();
			B63Block.registerRenderLayer();
			B64Block.registerRenderLayer();
			B86Block.registerRenderLayer();
			B87Block.registerRenderLayer();
			B88Block.registerRenderLayer();
			B102Block.registerRenderLayer();
			B103Block.registerRenderLayer();
			B107Block.registerRenderLayer();
			B108Block.registerRenderLayer();
			B110Block.registerRenderLayer();
			B111Block.registerRenderLayer();
			B112Block.registerRenderLayer();
			B113Block.registerRenderLayer();
			B120Block.registerRenderLayer();
			B121Block.registerRenderLayer();
			B124Block.registerRenderLayer();
			B125Block.registerRenderLayer();
			B127Block.registerRenderLayer();
			B128Block.registerRenderLayer();
			B129Block.registerRenderLayer();
			B130Block.registerRenderLayer();
			B131Block.registerRenderLayer();
			B136Block.registerRenderLayer();
			B135Block.registerRenderLayer();
			B137Block.registerRenderLayer();
			B138Block.registerRenderLayer();
			B141Block.registerRenderLayer();
			B143Block.registerRenderLayer();
			B144Block.registerRenderLayer();
			B145Block.registerRenderLayer();
			B148Block.registerRenderLayer();
			B149Block.registerRenderLayer();
			B158Block.registerRenderLayer();
			B159Block.registerRenderLayer();
			Meathookcod1Block.registerRenderLayer();
			Meathookcod2Block.registerRenderLayer();
			Fish1Block.registerRenderLayer();
			Fish2Block.registerRenderLayer();
			Sheep1Block.registerRenderLayer();
			SheepBlock.registerRenderLayer();
			Sheep2Block.registerRenderLayer();
			Sheep3Block.registerRenderLayer();
			PigBlock.registerRenderLayer();
			Pig1Block.registerRenderLayer();
			Pig2Block.registerRenderLayer();
			Pig3Block.registerRenderLayer();
			Pig0Block.registerRenderLayer();
			Cow0Block.registerRenderLayer();
			Cow3Block.registerRenderLayer();
			Cow2Block.registerRenderLayer();
			Cow1Block.registerRenderLayer();
			MeathookcoddryBlock.registerRenderLayer();
			B14Block.registerRenderLayer();
			B16Block.registerRenderLayer();
			B19Block.registerRenderLayer();
			B12Block.registerRenderLayer();
			B22Block.registerRenderLayer();
			B24Block.registerRenderLayer();
			B3Block.registerRenderLayer();
			B26Block.registerRenderLayer();
			B30Block.registerRenderLayer();
			B39Block.registerRenderLayer();
			B41Block.registerRenderLayer();
			B42Block.registerRenderLayer();
			B43Block.registerRenderLayer();
			B44Block.registerRenderLayer();
			B45Block.registerRenderLayer();
			D5Block.registerRenderLayer();
			D6Block.registerRenderLayer();
			B49Block.registerRenderLayer();
			B50Block.registerRenderLayer();
			B55Block.registerRenderLayer();
			B56Block.registerRenderLayer();
			B58Block.registerRenderLayer();
			B65Block.registerRenderLayer();
			B66Block.registerRenderLayer();
			B67Block.registerRenderLayer();
			B68Block.registerRenderLayer();
			B69Block.registerRenderLayer();
			B70Block.registerRenderLayer();
			B71Block.registerRenderLayer();
			B72Block.registerRenderLayer();
			B73Block.registerRenderLayer();
			B74Block.registerRenderLayer();
			B75Block.registerRenderLayer();
			B76Block.registerRenderLayer();
			B81Block.registerRenderLayer();
			B82Block.registerRenderLayer();
			B83Block.registerRenderLayer();
			B84Block.registerRenderLayer();
			B85Block.registerRenderLayer();
			B89Block.registerRenderLayer();
			B90Block.registerRenderLayer();
			B91Block.registerRenderLayer();
			B92Block.registerRenderLayer();
			B93Block.registerRenderLayer();
			B94Block.registerRenderLayer();
			B95Block.registerRenderLayer();
			B96Block.registerRenderLayer();
			B97Block.registerRenderLayer();
			B98Block.registerRenderLayer();
			Bb103Block.registerRenderLayer();
			B109Block.registerRenderLayer();
			B114Block.registerRenderLayer();
			B115Block.registerRenderLayer();
			B116Block.registerRenderLayer();
			B117Block.registerRenderLayer();
			B118Block.registerRenderLayer();
			B126Block.registerRenderLayer();
			B132Block.registerRenderLayer();
			B133Block.registerRenderLayer();
			B134Block.registerRenderLayer();
			B139Block.registerRenderLayer();
			B142Block.registerRenderLayer();
			B147Block.registerRenderLayer();
			B150Block.registerRenderLayer();
			B160Block.registerRenderLayer();
			B166Block.registerRenderLayer();
			B167Block.registerRenderLayer();
			B168Block.registerRenderLayer();
			B169Block.registerRenderLayer();
			B170Block.registerRenderLayer();
			B173Block.registerRenderLayer();
			B176Block.registerRenderLayer();
			B179Block.registerRenderLayer();
			B180Block.registerRenderLayer();
			D16Block.registerRenderLayer();
			D17Block.registerRenderLayer();
			D18Block.registerRenderLayer();
			D19Block.registerRenderLayer();
			D20Block.registerRenderLayer();
			D21Block.registerRenderLayer();
			D22Block.registerRenderLayer();
			D23Block.registerRenderLayer();
			D24Block.registerRenderLayer();
			D25Block.registerRenderLayer();
			D26Block.registerRenderLayer();
			D27Block.registerRenderLayer();
			D29Block.registerRenderLayer();
			A14Block.registerRenderLayer();
			A16Block.registerRenderLayer();
			A17Block.registerRenderLayer();
			A21Block.registerRenderLayer();
			D30Block.registerRenderLayer();
			D31Block.registerRenderLayer();
			D32Block.registerRenderLayer();
			D33Block.registerRenderLayer();
			D34Block.registerRenderLayer();
			D35Block.registerRenderLayer();
			D36Block.registerRenderLayer();
			D37Block.registerRenderLayer();
			D38Block.registerRenderLayer();
			D39Block.registerRenderLayer();
			D41Block.registerRenderLayer();
			D40Block.registerRenderLayer();
			D42Block.registerRenderLayer();
			D43Block.registerRenderLayer();
			D45Block.registerRenderLayer();
			D44Block.registerRenderLayer();
			D46Block.registerRenderLayer();
			D47Block.registerRenderLayer();
			D48Block.registerRenderLayer();
			D49Block.registerRenderLayer();
			D50Block.registerRenderLayer();
			D51Block.registerRenderLayer();
			D52Block.registerRenderLayer();
			D53Block.registerRenderLayer();
			D54Block.registerRenderLayer();
			D55Block.registerRenderLayer();
			D56Block.registerRenderLayer();
			D57Block.registerRenderLayer();
			D58Block.registerRenderLayer();
			D59Block.registerRenderLayer();
			D60Block.registerRenderLayer();
			D61Block.registerRenderLayer();
			D62Block.registerRenderLayer();
			D63Block.registerRenderLayer();
			D64Block.registerRenderLayer();
			D65Block.registerRenderLayer();
			D66Block.registerRenderLayer();
			D67Block.registerRenderLayer();
			D68Block.registerRenderLayer();
			D69Block.registerRenderLayer();
			D70Block.registerRenderLayer();
			D80Block.registerRenderLayer();
			D71Block.registerRenderLayer();
			D72Block.registerRenderLayer();
			D73Block.registerRenderLayer();
			D74Block.registerRenderLayer();
			D75Block.registerRenderLayer();
			D76Block.registerRenderLayer();
			D77Block.registerRenderLayer();
			B183Block.registerRenderLayer();
			B184Block.registerRenderLayer();
			B185Block.registerRenderLayer();
			B186Block.registerRenderLayer();
			B187Block.registerRenderLayer();
			B188Block.registerRenderLayer();
			B189Block.registerRenderLayer();
			B190Block.registerRenderLayer();
			B191Block.registerRenderLayer();
			B192Block.registerRenderLayer();
			B193Block.registerRenderLayer();
			B194Block.registerRenderLayer();
			B195Block.registerRenderLayer();
			B196Block.registerRenderLayer();
			B197Block.registerRenderLayer();
			B198Block.registerRenderLayer();
			B199Block.registerRenderLayer();
			B200Block.registerRenderLayer();
			B201Block.registerRenderLayer();
			B205Block.registerRenderLayer();
			B206Block.registerRenderLayer();
			B207Block.registerRenderLayer();
			D78Block.registerRenderLayer();
			B208Block.registerRenderLayer();
			B209Block.registerRenderLayer();
			B210Block.registerRenderLayer();
			B211Block.registerRenderLayer();
			D79Block.registerRenderLayer();
			D81Block.registerRenderLayer();
			D82Block.registerRenderLayer();
			LudengBlock.registerRenderLayer();
			B212Block.registerRenderLayer();
			B214Block.registerRenderLayer();
			B215Block.registerRenderLayer();
			B217Block.registerRenderLayer();
			B218Block.registerRenderLayer();
			B220Block.registerRenderLayer();
			B221Block.registerRenderLayer();
			B222Block.registerRenderLayer();
			B226Block.registerRenderLayer();
			B227Block.registerRenderLayer();
			W31Block.registerRenderLayer();
			W32Block.registerRenderLayer();
			W33Block.registerRenderLayer();
			W34Block.registerRenderLayer();
			W35Block.registerRenderLayer();
			W38Block.registerRenderLayer();
			B228Block.registerRenderLayer();
			B229Block.registerRenderLayer();
			Guiyugou1Block.registerRenderLayer();
			Guiyugou2Block.registerRenderLayer();
			Guiyugou3Block.registerRenderLayer();
			Guiyugou4Block.registerRenderLayer();
			B232Block.registerRenderLayer();
			B233Block.registerRenderLayer();
			B234Block.registerRenderLayer();
			B235Block.registerRenderLayer();
			B236Block.registerRenderLayer();
			B238Block.registerRenderLayer();
			B239Block.registerRenderLayer();
			B240Block.registerRenderLayer();
			B238T1Block.registerRenderLayer();
			B238T2Block.registerRenderLayer();
			B238T3Block.registerRenderLayer();
			B239T1Block.registerRenderLayer();
			B239T2Block.registerRenderLayer();
			B239T3Block.registerRenderLayer();
			B240T1Block.registerRenderLayer();
			B240T2Block.registerRenderLayer();
			B240T3Block.registerRenderLayer();
			B241Block.registerRenderLayer();
			B241aBlock.registerRenderLayer();
			B242Block.registerRenderLayer();
			B242aBlock.registerRenderLayer();
			B243Block.registerRenderLayer();
			B243aBlock.registerRenderLayer();
			B244Block.registerRenderLayer();
			B1Block.registerRenderLayer();
			B245Block.registerRenderLayer();
			B247Block.registerRenderLayer();
			B248Block.registerRenderLayer();
			B249Block.registerRenderLayer();
			B250Block.registerRenderLayer();
			B246Block.registerRenderLayer();
			B252Block.registerRenderLayer();
			B253Block.registerRenderLayer();
			B254Block.registerRenderLayer();
			B255Block.registerRenderLayer();
			B256Block.registerRenderLayer();
			B258Block.registerRenderLayer();
			B259Block.registerRenderLayer();
			B260Block.registerRenderLayer();
			B261Block.registerRenderLayer();
			B262Block.registerRenderLayer();
			B266Block.registerRenderLayer();
			B267Block.registerRenderLayer();
			B268Block.registerRenderLayer();
			B270Block.registerRenderLayer();
			B272Block.registerRenderLayer();
			B273Block.registerRenderLayer();
			B274Block.registerRenderLayer();
			B275Block.registerRenderLayer();
			B278Block.registerRenderLayer();
			B279Block.registerRenderLayer();
			B280Block.registerRenderLayer();
			B281Block.registerRenderLayer();
			B282Block.registerRenderLayer();
			B283Block.registerRenderLayer();
			B284Block.registerRenderLayer();
			B285Block.registerRenderLayer();
			A29Block.registerRenderLayer();
			A30Block.registerRenderLayer();
			A31Block.registerRenderLayer();
		}
	}
}
